### ISSUE TITLE
Using Microsoft.AspNetCore.Mvc package affected by Microsoft Security Advisory 4021279

### ISSUE THREAD

**Issue by ChrisBriggsy** [JasonGT/NorthwindTraders#1]
Hi @JasonGT, 

Noticed that your project has a dependency on a version of the Microsoft.AspNetCore.Mvc package that has been marked as affected in [Microsoft Security Advisory 4021279: Vulnerabilities in .NET Core, ASP.NET Core Could Allow Elevation of Privilege](https://github.com/dotnet/announcements/issues/12).

Chris

**Comment by JasonGT** [comment]
HI @ChrisBriggsy 

Thanks for the heads up, I've upgraded all dependencies to the latest version.

Jason
