### ISSUE TITLE
WebUI is unresponsive

### ISSUE THREAD

**Issue by RudyCo** [JasonGT/NorthwindTraders#10]
Hello, I am trying to launch the WebUI project but the web app is unresponsive. I can see the Dashboard but when I click on any menu item, the web app do not load anything.
Any idea?
Thanks!

**Comment by JasonGT** [comment]
Sorry for the confusion, the front end hasn't been developed... right now it is just some static pages. If you can see the dashboard it is working as expected. I am hoping to get back to it soon.
