### ISSUE TITLE
Invert dependency on persistence.

### ISSUE THREAD

**Issue by JasonGT** [JasonGT/NorthwindTraders#100]
Currently the Application layer depends on the Persistence layer. This was a design choice, trading simplicity now for complexity later.

Update the design to invert the dependency on Persistence using a simple INotificationsDbContext. The result being that the dependency is inverted (change) but that Application will still depend on EF Core (no change).

**Comment by jespersh** [comment]
https://github.com/JasonGT/NorthwindTraders/blob/944f49b0784943ac626e6f4be17a56a66c62fe0e/Northwind.Application/Northwind.Application.csproj#L20-L24

Should be replaced with
`<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0" />`

Couldn't build otherwise

**Comment by JasonGT** [comment]
Thanks Jesper

**Comment by ducva** [comment]
I tried to add Identity as below
```
services.AddDefaultIdentity<User>().AddRoles<Role>().AddEntityFrameworkStores<NorthwindDbContext>();
```

then, in Application, in Command Handler, I injected `UserManager<User>`. But it failed because I cannot resolve NorthwindDbContext.

I guess the problem comes from here
```
// Add DbContext using SQL Server Provider
services.AddDbContext<INorthwindDbContext, NorthwindDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("NorthwindDatabase")));

```
How can I resolve it?

**Comment by Jhanbury** [comment]
@JasonGT  I know you have your Domain models and Application logic separated for a reason, but if you combined them into a single project you could use then use the repository pattern to remove your dependency on Entity Framework.

I know I may be opening a can of worms with the repository pattern but in this case, it would be aiding the project by removing a dependency on a single ORM.

I think Steve Smiths template does something very similar using a [generic repository](https://github.com/ardalis/CleanArchitecture/blob/master/src/CleanArchitecture.Core/Interfaces/IRepository.cs)

This is just an idea and if there are other trade offs that conflict with this approach I understand. 
I would love to hear your thoughts on this approach

**Comment by ChuckBryan** [comment]
I think Jason falls on the side of "if the repository pattern fits a need in your application, by all means use it." However, since Repository is typically used to abstract your data access, and EF is essentially a database abstraction (DbSets are repositories, DbContext is a UoW), it is not as helpful as it once was. 

At least, that was the direction from his NDC video.

I love Steve Smith's Repository and Specification guidance, but, in use, it seems to be way more effort that just using EF directly within Commands and Queries. Just my thoughts though.

**Comment by Jhanbury** [comment]
@ChuckBryan I totally agree with your points. It seems that UoW and Repos are no longer the go-to patterns that a lot of developers used.
The only thing is that this architecture still has a reference to an ORM which is not ideal. It now only adds you the flexibility of whatever EF core supports (which is a lot so again trade-offs). I'm just looking at what could be done to remove this dependency and allow the domain to be decoupled from any database technology.

**Comment by ChuckBryan** [comment]
Even still, I think you are getting Persistence Ingnorance - even if you are injecting EF/NH into your application layer the Domain Entities still have no clue that they are being saved because there is no database code (e.g. like Active Record) in them.

**Comment by stevensrf11** [comment]
I downloaded this project and ran the Northwind.WebUI project and it just hangs. The blank webpage is shown in IE and the visual studio project locks up. I also tried changing the connection string to a local northwind database  and the project times  out on the error  "Cannot connect to runtime process time out after  10000 ms reason connect to the target: connect econnrefused 127.0.0.1:2015

**Comment by stevensrf11** [comment]
I followed the steps list below. 
Why am I having to clone a repository and run the command line npm start within the Northwind.WebUI\ClientApp?

Why can I just restore nuget packages and run the client app and up pops the browser showing the application working? 

When the npm starting command line did not work any way 
The following errors occureed
C:\code\NorthwindTraders-master\NorthwindTraders-master\Northwind.WebUI>npm start
npm ERR! path C:\code\NorthwindTraders-master\NorthwindTraders-master\Northwind.WebUI\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\code\NorthwindTraders-master\NorthwindTraders-master\Northwind.WebUI\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\spaceradar\AppData\Roaming\npm-cache\_logs\2019-04-16T21_47_47_468Z-debug.log



  1. Clone the repository
  2. At the root directory, restore required packages by running:
     ```
     dotnet restore
     ```
  3. Next, build the solution by running:
     ```
     dotnet build
     ```
  4. Next, within the `Northwind.WebUI\ClientApp` directory, launch the front end by running:
     ```
     npm start
     ```
  5. Once the front end has started, within the `Northwind.WebUI` directory, launch the back end by running:
     ```
	 dotnet run
	 ```
  5. Launch [http://localhost:52468/](http://localhost:52468/) in your browser to view the Web UI
  
  6. Launch [http://localhost:52468/api](http://localhost:52468/api) in your browser to view the API

**Comment by jespersh** [comment]
@stevensrf11 create a separate issue
