### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by PeterJD** [JasonGT/NorthwindTraders#101]
Hi
 I noticed in EmployeesWithManagersQueryHandler you inserted SQL code directly in the method
Why would you do this?
 Is not this dangerous?

Kind regards

**Comment by JasonGT** [comment]
Hi Peter,

Thanks for the question. This code is using Dapper to project directly to a view model - EmployeeManagerModel. The benefit is performance. Using tools such as Dapper or EF Core Query Types can result in more performant queries.

It is safe to do so, as long as you parametise your input. You can learn more here;

- https://docs.microsoft.com/en-us/ef/core/modeling/query-types
- https://github.com/StackExchange/Dapper

Thanks.
