### ISSUE TITLE
How to write a unit test for a command that DI Mediator

### ISSUE THREAD

**Issue by qazq** [JasonGT/NorthwindTraders#102]
Hi,

`CreateCustomerCommand.cs` DI Mediator to publish customer created event. If I want to write a unit test for this, how can I create a Mediator instance for it?

Thanks.

**Comment by rafalschmidt97** [comment]
I would go into mocking Mediatr or if you wanna test everything then go into Integration tests. I don't see any advantages of testing only command + events rather than mocking/integration.

Good luck 😅

**Comment by JasonGT** [comment]
I've added an example unit test, hope this helps, sorry for the delay!
