### ISSUE TITLE
JsonIgnore for Entity classes

### ISSUE THREAD

**Issue by lokesh-selvaraj** [JasonGT/NorthwindTraders#103]
Hi Jason,

I have a question, suppose if I happen to serialize any of the properties of an entity class provided it has a 1-many relationship with another concrete class of Domain Layer would you simply use the JsonIgnore attribute using Newtonsoft.Json or something else ?

Thanks,
Lokesh

**Comment by JasonGT** [comment]
I imagine that you're running into a circular reference during serialisation and want to avoid this issue. My recommendation is not to send / receive entities during requests / responses. This can result in a multitude of issues, such as security (https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Mass_Assignment_Cheat_Sheet.md), circular references when serializing, and forcing the client to make additional requests (something avoided in the example below).

When you are considering the type to return to the client, you need to consider the needs of the view. For example, if editing a product, the product entity itself is not sufficient. You will need 1) a list of categories, 2) a list of suppliers, 3) details of the product. The best type to return in this case would be an EditProductViewModel as follows:

```
public class EditProductVm
{
  public IList<Category> Categories { get; set; }
  public IList<Supplier> Suppliers { get; set; }

  public int Id  { get; set; }
  public string Name  { get; set; }

 // Additional properties omited.
}
```

This VM provides everything the client will need to display the Edit Product View. Typically, you should try to have a one to one mapping between your view and view models.

Hope this helps.

**Comment by lokesh-selvaraj** [comment]
Thanks for your inputs, All the best !!!
