### ISSUE TITLE
Should there be an abstraction for Commands and Queries?

### ISSUE THREAD

**Issue by awesomeaaron** [JasonGT/NorthwindTraders#105]
Hi,

Just wondering if it will be a good idea to extend Command and Queries from an abstraction which initializes `DbContext` and `IMapper` so we do not have to duplicate them?

**Comment by awesomeaaron** [comment]
An example
```
public abstract class MVCRequestHandler<T,E> : IRequestHandler<T,E> where T : IRequest<E>
{
        protected MVCRequestHandler(ApplicationDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper
        }
        
        protected ApplicationDbContext _dbContext;
        protected IMapper _mapper;

        public abstract Task<E> Handle(T request, CancellationToken cancellationToken);
}
```

**Comment by JasonGT** [comment]
Hi, thanks for the suggestion. Please can you provide an example of a derived command or query?

**Comment by rafalschmidt97** [comment]
@awesomeaaron - I think it's not useful that much - not all of your commands and queries need all this properties - sometimes you don't use mapper or logger (or even dbcontext if you only get data from cache). It means that you'll provide to your requests resources it doesn't need.

**Comment by awesomeaaron** [comment]
@rafalschmidt97 Agreed. It will be useful for CRUD operations on entities. You can choose not to extend from this class in other cases but my point was if there is enough code repetition, it can be abstracted out.

**Comment by awesomeaaron** [comment]
@JasonGT A simple approach will be something like

```
public class GetProductByIdQueryHandler : MVCRequestHandler<GetProductByIdQuery, ProductDTO>
   
    {
        public GetProductByIdQueryHandler(ApplicationDbContext dbContext, IMapper mapper, ILogger logger) : base(dbContext, mapper, logger)
        {

        }
        
        public override async Task<ProductDTO> Handle(GetProductByIdQuery request, CancellationToken cancellationToken)
        {
            var product = await DbContext.Products.FirstOrDefaultAsync(p => p.Id == request.Id, cancellationToken);

            ...
        }
    }
```

But I think a better solution will be use the same approach as in https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.WebUI/Controllers/BaseController.cs for Mediator so we do not have to call the constructor explicitly.

**Comment by JasonGT** [comment]
Yes maybe a base class that exposes the common dependencies via property injection. Thanks for the suggestion.
