### ISSUE TITLE
Authentication and authorization in this architecture

### ISSUE THREAD

**Issue by hanyassar4098** [JasonGT/NorthwindTraders#107]
Thanks for sharing the details , but I need to know how can I implement the authorization and authentication as the validation handled in example.thank you

**Comment by hakimio** [comment]
It's on the roadmap -> https://github.com/JasonGT/NorthwindTraders/projects/1

**Comment by JasonGT** [comment]
It in progress, hope to get it to you soon. Please see #92.

**Comment by hanyassar4098** [comment]
Thanks,please what about how handle master and details like order& order
details . Another point is the first version contain employee manager view
model it have been discarded from the latest version of the app ..whay it
removed ?

في الأربعاء، ١٠ أبريل، ٢٠١٩ ١:١١ ص Jason Taylor <notifications@github.com>
كتب:
