### ISSUE TITLE
Entity properties are tracked and don't need to call DbSet<>.Update(entity)

### ISSUE THREAD

**Issue by jespersh** [JasonGT/NorthwindTraders#108]
In `UpdateCustomerCommandHandler.Handle`, when you get an entity from DbSet<Customer> and change the property values of the entity, then you don't need to call 
`_context.Customers.Update(entity);`
Update() invalidates all the fields.

From: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.update?view=efcore-2.1
> All properties of the entity will be marked as modified.

Just calling `await _context.SaveChangesAsync(cancellationToken);` is enough here.

Thanks for your example project, learned a lot.

**Comment by JasonGT** [comment]
Thanks, I had been meaning to fix this one but kept forgetting! Much appreciated.
