### ISSUE TITLE
Failing to get the context in Program.cs

### ISSUE THREAD

**Issue by ahundiak** [JasonGT/NorthwindTraders#109]
As part of introducing an interface for the context you changed Startup.cs to:

    services.AddDbContext<INorthwindDbContext, NorthwindDbContext>(options =>

The problem is that in Program.cs:

    var context = scope.ServiceProvider.GetService<NorthwindDbContext>();

returns a null for me.  I cloned your solution and just pressed the build solution button.  Pretty sure I did not change anything.  Verified I'm using 2.2 etc.  Ran into the same thing when I tried to duplicate your solutions structure.

I poked around a bit and really could not find an example of passing both an interface as well as an implementation to AdDbContext.  The signature is documented but there is no more details on it.  And my source code reading skills are sadly limited.

Any thoughts on what I am doing wrong?

**Comment by JasonGT** [comment]
Thanks I missed this! What I've done is to request INorthwindDbContext and cast to NorthwindDbContext for the purposes of seeding.
