### ISSUE TITLE
[Feature request] File Upload

### ISSUE THREAD

**Issue by kevinleptin** [JasonGT/NorthwindTraders#111]
In my understanding, adding a uploading file feature will make the Northwind project more perfect.

**Comment by rafalschmidt97** [comment]
@kevinleptin - Would you like to see file uploading into cloud or local (for example wwwroot/uploads)? Any restrictions like ONLY PHOTOS or something else? Be more precise 🚀

**Comment by LucaGabi** [comment]
Local (wwwroot/uploads) first! 
:)

**Comment by phatvt** [comment]
I have a problem about update file feature (wwwroot/uploads). I want to bind IFormFile interface to my ViewModel so where my ViewModel should be placed, Presentation or Application layer?

**Comment by rafalschmidt97** [comment]
> I have a problem about update file feature (wwwroot/uploads). I want to bind IFormFile interface to my ViewModel so where my ViewModel should be placed, Presentation or Application layer?

In my humble opinion you should use IFormFile only in presentation layer and pass Streams into app. Here I've prepared for you how can it look (of course you can disagree with me):

```c#
public class UploadsController : BaseController
  {
    [HttpPost]
    public async Task<IActionResult> Upload()
    {
      var files = Request.Form.Files;

      if (files.Count <= 0)
      {
        throw new BadRequestException("Unsupported media type. File required.");
      }

      var file = files[0];
      var request = new UploadPhotoCommand(file.FileName, file.OpenReadStream());

      var url = await Mediator.Send(request);
      return Ok(new { url });
    }
  }
```

**Comment by JasonGT** [comment]
Thanks for the question. This would make a good feature, especially for uploading employee photos and category images. I really like @rafalschmidt97 's approach, recommend following it. I've added this to the roadmap, so I'll try to add an example in the future. Thanks.
