### ISSUE TITLE
I am not able to do a pull request.

### ISSUE THREAD

**Issue by amitdixit** [JasonGT/NorthwindTraders#112]
I am running the application from 2 separate power shell command prompt(dotnet run and ng serve) the api url is always "localhost:4200" (because the baseUrl is null) and not the actual API; Guess there is some issue with new InjectionToken<string>('API_BASE_URL') or new InjectionToken<string>('http://localhost:52468').

Hence tried the below approach :
export interface Config {
  apiUrl: string;
}

export const AppConfig: Config = {
  apiUrl: 'http://localhost:52468'
};

export const API_BASE_URL = new InjectionToken<Config>
  ('appConfig', {
    providedIn: 'root',
    factory: () => AppConfig
  });
 and  in the service constructor:
 constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) config?: Config) {
  //  console.log(config)
        this.http = http;
    this.baseUrl = config.apiUrl ? config.apiUrl : "";
    };

Also had to enable CORS on the API end to get this working.

**Comment by JasonGT** [comment]
The steps to launch are detailed here; https://github.com/JasonGT/NorthwindTraders/blob/master/ReadMe.md. 

You shouldn’t need to do more. Let me know if this still doesn’t work for you.
