### ISSUE TITLE
I think now it's time to introduce Event Source

### ISSUE THREAD

**Issue by amitdixit** [JasonGT/NorthwindTraders#113]
I think we can now introduce the concept of Event Sourcing to make this project more closer to Event Driven

**Comment by JasonGT** [comment]
Thanks for the suggestion, however this is not a concept that I want to demonstrate as part of this repo. If you were interested in learning more, this course covers it well - https://www.pluralsight.com/courses/modern-software-architecture-domain-models-cqrs-event-sourcing
