### ISSUE TITLE
Implement several examples to the client application

### ISSUE THREAD

**Issue by ValerianHavaux** [JasonGT/NorthwindTraders#115]
I would like to implement several examples to the client application.

Would you be interested ?

Like this for example : #114

**Comment by JasonGT** [comment]
That would be awesome! You can see some Vue examples here; https://github.com/devworkshops/vuejs-minnesota-2019/tree/master/northwind-traders/src/views. 

Let me know if you’re still keen.

**Comment by JasonGT** [comment]
As per above comment, I will be happy to accept a pull request for additional client apps or examples. Thanks!
