### ISSUE TITLE
Question: Can we remove relation definitions from Configurations?

### ISSUE THREAD

**Issue by Hameds** [JasonGT/NorthwindTraders#117]
As you know there are some conventions in EF Core for table relations. So if we use EF conventions in `Domain` project, is it necessary to write code for those relations in `Configuration` classes in `Persistence` project too?

**Comment by rafalschmidt97** [comment]
But conventions don't cover all "settings". For example CascadeDelete or ConcurrencyToken. Of course if you use Attributes instead of configuration files you don't need them (taking into consideration limitations of attributes) 🚀 I don't mark ID as primary key because of the convention but there are many other things to setup like indexes.

**Comment by Hameds** [comment]
@rafalschmidt97 sure. conventions don't cover everything. I don't want to use Attributes. I am talking about **relations**. for example take a look at these lines in `Order` class https://github.com/JasonGT/NorthwindTraders/blob/943a7ab24c4ce4c9c1b6b15a7bb1aa4d3451c2fb/Northwind.Domain/Entities/Order.cs#L14

https://github.com/JasonGT/NorthwindTraders/blob/943a7ab24c4ce4c9c1b6b15a7bb1aa4d3451c2fb/Northwind.Domain/Entities/Order.cs#L28

I think we don't need this in `OrderConfiguration` because of conventions https://github.com/JasonGT/NorthwindTraders/blob/943a7ab24c4ce4c9c1b6b15a7bb1aa4d3451c2fb/Northwind.Persistence/Configurations/OrderConfiguration.cs#L43-L46

**Comment by rafalschmidt97** [comment]
@Hameds - yeah. You're right. It is not necessary 😊 Maybe @JasonGT wanted to have specific names for constrains. Dunno. But it is a good staring point for the refactor 😄

**Comment by JasonGT** [comment]
The original database was scaffolded from SQL Server. As you’ve noted, some of the configuration generated is redundant as it is covered by a convention. 

It would be great to cleanup, but I have some other features on my list I’d like to implement first. I’ll add it to the roadmap.

**Comment by JasonGT** [comment]
This is done, refer to the above commit. The only difference in some cases were the specific names for the constraints (from the original Northwind database). Where it made sense I removed those configurations and went with conventions. Thanks.
