### ISSUE TITLE
Question: Registering Validators using AddFluentValidation

### ISSUE THREAD

**Issue by ron-camaron** [JasonGT/NorthwindTraders#119]
In Startup.cs file, the FluentValidation is setup for CreateCustomerCommandValidator as follows:

```
services.AddMvc(options => options.Filters.Add(typeof(CustomExceptionFilterAttribute)))
.SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CreateCustomerCommandValidator>());
```

This is just an example of how the Validator classes should be injected, right?

I mean, I should do the same for, for instance, DeleteCustomerCommandValidator. 

Am I right?

**Comment by equuskk** [comment]
I think you shouldnt
```csharp
/// <summary>
/// Registers all validators derived from AbstractValidator within the assembly containing the specified type
/// </summary>
public FluentValidationMvcConfiguration RegisterValidatorsFromAssemblyContaining<T>() {
	return RegisterValidatorsFromAssemblyContaining(typeof(T));
}
```

link :https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcConfiguration.cs
>

**Comment by ron-camaron** [comment]
Oooohh I got it! Of course. It makes sense. 

It registers all Validators in the assembly that contains the given class, so by providing only one class, the rest of Validators will be registered as well /)_-)

Thanks @equuskk for showing the right and obvious answer.
