### ISSUE TITLE
Question: How could I configure multiple Angular client apps?

### ISSUE THREAD

**Issue by filipeteotonio** [JasonGT/NorthwindTraders#120]
There is a 'ClientApp' folder in the WebUI project which contains the Angular application. I want to know if it is possible to add new one, eg. 'SecondClientApp' and have .NET core serving it alongside with the first one. If yes, how could I configure it in the Startup?

**Comment by aefox** [comment]
Hi @filipeteotonio ,

I recommend you visit these concepts of app pipeline found [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2) for in depth details about my example below (FYI: [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2#use-run-and-map) is the exact section you're interested in, but I strongly suggest starting from the start).

You can define multiple `spa`s in `Northwind.WebUI.Startup.cs` Configure method, at the end, like this:
```C#
app.Map("/app1", app =>
{
  app.UseSpa(spa =>
  {
    // SPA1 configuration
  });
}

app.Map("/app2", app =>
{
  app.UseSpa(spa =>
  {
    // SPA2 configuration
  });
}
```

Now, whenever you'll hit `/app1` you'll actually get the SPA1 files or SPA2 files if you hit `/app2`.

FYI: this is a .net question, so I suggest that if the question is not relevant to this repository to post on SO. Cheers!

**Comment by filipeteotonio** [comment]
Hey @aefox, thank you very much. Yes, my question is not really related to the repo, sorry for that. 😅
