### ISSUE TITLE
Question: What should Update return?

### ISSUE THREAD

**Issue by mrtank** [JasonGT/NorthwindTraders#122]
Hi,

What should Update return?

- Product's Update returns `ActionResult<ProductDto>`, but the Handler is defined like `public async Task<Unit> Handle(UpdateProductCommand request, CancellationToken cancellationToken)`.
- Customer's Update returns `NoContent()`
- There is a `[HttpPut("{id}")]` annotation on the Update command.

**Comment by NerijusD** [comment]
Hi.

There are several practices. Personally, I like the idea of returning `dto` of entity after update for very simple reason - efficiency. When `PUT`/`POST` route returns no data, we have to make additional `GET` request to get updated entity. Why not to get right after `PUT` request? In this way we are saving one extra http request per every `PUT`/`POST` request.

**Comment by JasonGT** [comment]
Thanks for pointing out this issue, I've added a fix. I've changed the return type for Product Update to NoContent. In general, I'd recommend following these guidelines https://stackoverflow.com/a/43493623. But as @NerijusD has pointed out - it can depend on the needs of the client.
