### ISSUE TITLE
Request: Cross-Entity Domain Logic Example

### ISSUE THREAD

**Issue by vafreebird** [JasonGT/NorthwindTraders#125]
First, thank you for this repository.  I'm porting one of my applications to these patterns and its going very well.

I was hoping to get your thoughts on how to implement a certain type of domain logic that isn't bound to a single entity.  Let's say I have an entity called Order with a Status property.  This Status property can and should be determined by the states of related entities.  For instance, an Order has multiple OrderItems and multiple OrderShipments.  Each OrderItem has a Status and each OrderShipment has a Status.  Disregarding the details, let's assume an algorithm exists to determine the Order Status using these child Statuses.

Let's say the Application project has these two features: UpdateOrderShipment and UpdateOrderItem.  Each one effectively allows changing their respective statuses.  Both should cause the algorithm to execute and potentially update the Order status as well.

I feel like this is a domain rule and should be implemented there.  I'm just not sure what the best approach would be for how that code should be structured, instantiated and executed.  By the DbContext's SaveChangesAsync method?  I'm thinking of creating an interface for essentially a trigger and having the context load these "triggers" and call them before the base Save occurs but it seems as though the persistence and domain are getting muddled.

How would you approach this?

Thank you!

**Comment by siriak** [comment]
Thank you for such a great question! It gave me some food for thought and I think that I have an answer for you. What you described, sounds much like an aggregate pattern in DDD. Even more, I found an article on this topic by Martin Fowler (https://martinfowler.com/bliki/DDD_Aggregate.html).

**Comment by siriak** [comment]
Thank you for such a great question! It gave me some food for thought and I think that I have an answer for you. What you described, sounds much like an aggregate pattern in DDD. Even more, I found an article by Martin Fowler on this topic (https://martinfowler.com/bliki/DDD_Aggregate.html).

> Aggregate is a pattern in Domain-Driven Design. A DDD aggregate is a cluster of domain objects that can be treated as a single unit. An example may be an order and its line-items, these will be separate objects, but it's useful to treat the order (together with its line items) as a single aggregate.

> An aggregate will have one of its component objects be the aggregate root. Any references from outside the aggregate should only go to the aggregate root. The root can thus ensure the integrity of the aggregate as a whole.

Anyway, it's interesting to me what @JasonGT thinks about it, so I'm waiting for his reply.

**Comment by vafreebird** [comment]
Thank you for the link.  I'll research the pattern more in-depth, but I have a couple of questions based on 
my initial read.  The first is simply how would this pattern be applied using this type of architecture.  Would the logic be placed inside the Order domain class and does that mean the child collections have to be managed through methods on the Order class so it can evaluate changes as they are made?

Also, I'm concerned the example I provided was too simple.  I simplified a real-world scenario I'm dealing with for my original post.  My example mirrors the model in the following image (each box represents a table):
![image](https://user-images.githubusercontent.com/37149609/58709133-82cff080-8387-11e9-87de-0cc3458299ab.png)
If I update my original question with this model in mind, each Child has its own status.  Child A's status can be determined by an algorithm that looks at related Child B and Child C records through their direct relationships with Child A.

My concern is this statement from the pattern: 
> Any references from outside the aggregate should only go to the aggregate root. The root can thus ensure the integrity of the aggregate as a whole.

There are many operations against the Child entities (and their own children) that do not affect the other entities in this diagram.  It seems counter productive to have to content with the entire root structure during these operations.  Would it make sense to treat this collection of entities as an aggregate only when updating a property of an entity that could have a cascading effect on another entity?

**Comment by siriak** [comment]
> Would the logic be placed inside the Order domain class and does that mean the child collections have to be managed through methods on the Order class so it can evaluate changes as they are made?

Yes, you got the point of this pattern right.

> There are many operations against the Child entities (and their own children) that do not affect the other entities in this diagram. It seems counter productive to have to content with the entire root structure during these operations. Would it make sense to treat this collection of entities as an aggregate only when updating a property of an entity that could have a cascading effect on another entity?

This would make sense, but how do you know which operations _could_ have a cascading effect? This is business logic that should be placed at the aggregate root, it shouldn't be leaked outside as it is subject to change. What if you try lazy loading for these additional entities?

**Comment by JasonGT** [comment]
Great question. As per above suggestion implementing aggregates is a good way to go, you can learn more here; https://kalele.io/modeling-aggregates-with-ddd-and-entity-framework/.

An alternate approach to consider is to have the relevant commands raise notifications using MediatR. The notification could reprepresent a state change such as OrderAdded or OrderItemModified or OrderStatusChanged. Using MediatR, you can then associate one or more notification handlers to the notification. This handler can be used to manage the shared logic. You can learn more here; https://github.com/jbogard/MediatR/wiki#publishing. As an example you can look at https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.Application/Customers/Commands/CreateCustomer/CreateCustomerCommand.cs. It raises a CustomerCreated notification.

Hope this helps, good luck with your project. :)

**Comment by torturegenitale** [comment]
@JasonGT You would then call another SaveChanges in the CustomerCreated Handler?

**Comment by GFoley83** [comment]
The command handler would have a `SaveChanges` call but the notification handler(s) should definitely not be calling `SaveChanges` again, as command handlers are atomic in nature. You would only call `SaveChanges` once and after that has ran successfully, then you would dispatch your `CustomerCreated` event, as shown here:

https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Application/Customers/Commands/CreateCustomer/CreateCustomerCommand.cs#L64

Besides this however, you could still potentially end up with inconsistent data, depending on the type of resiliency needed. For example, whether or not you can ignore, retry, undo failures and at which points in the large transaction. For answers to those questions, I suggest you read a series of posts by Jimmy Bogard on this very topic:

https://jimmybogard.com/refactoring-towards-resilience-a-primer/
