### ISSUE TITLE
specification.json not updating

### ISSUE THREAD

**Issue by elcondedebahia** [JasonGT/NorthwindTraders#127]
When running the application, I can't see any change in the models in Swagger, thus Nswag won't update the services. 
I found out that specification.json is never updated. Did someone got into the same issue?

**Comment by JasonGT** [comment]
Thanks for reporting, I actually had that build action commented out.

**Comment by elcondedebahia** [comment]
Hey Jason, can you please let me know how to enable it back? Thanks

**Comment by JasonGT** [comment]
You can find the MSBuild Action within https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.WebUI/Northwind.WebUI.csproj.

The following block does the work:
<Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core22) run /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>

To fix your version, uncommonly this block.

Or you can get latest from the repo.

I describe this in more detail here; http://www.codingflow.net/building-single-page-applications-on-asp-net-core-2-2/.
________________________________

**Comment by elcondedebahia** [comment]
Thanks Jason, you're the best. I haven't checked the latest version for the change. Regards!
