### ISSUE TITLE
Using Repository pattern in this solution.

### ISSUE THREAD

**Issue by amitdixit** [JasonGT/NorthwindTraders#130]
How can we implement Using Repository pattern in this solution.

**Comment by rasmuseeg** [comment]
To my understanding your DbContext is your repository.

**Comment by rafalschmidt97** [comment]
Keep interfaces for repos in app layer (for example IUsersRepository) and implementations in Persistence (UsersRepository). I really like repository pattern - it's a simple solution to make your project persistence ignorance. In implementation you can you EF or Dapper - it doesn't matter. Of course you have to somehow add it into di. For instance you can use [Scrutor](https://github.com/khellang/Scrutor):

```c#
      var persistenceAssembly = typeof(UsersRepository).GetTypeInfo().Assembly;

      services.Scan(scan =>
        scan.FromAssemblies(persistenceAssembly)
          .AddClasses()
          .AsMatchingInterface());
```

**Comment by amitdixit** [comment]
Actually my architecture is Something like Handlers=>Service Layer=>Repository Layer

**Comment by kubano** [comment]
> To my understanding your DbContext is your repository.

DbContext id your UOW, DbSet is your repo (y)

**Comment by JasonGT** [comment]
It's relatively straight forward in the current design. I'd suggest following @rafalschmidt97's recommendations and taking a look at this implementation - https://deviq.com/repository-pattern/.
