### ISSUE TITLE
Functional tests - Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Application.Infrastructure.RequestLogger`

### ISSUE THREAD

**Issue by alvipeo** [JasonGT/NorthwindTraders#131]
Hi,

thank you for your great talks and the project!
I've been trying to use this but one thing doesn't work in functional test. When I run a functional test in my project (which is based on this one as you can imagine) I get this:

>> Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Prj.Application.Infrastructure.RequestLogger`1[Prj.PageBlocks.Commands.CreatePageBlockCommand]'.

The only dependency I have on the ILogger is in RequestPerformanceBehaviour.

I'm missing on how to make the ILogger available in tests.

**Comment by alvipeo** [comment]
ok, I fixed this in my project. And I have no #$%#$% idea how :(( I'd really like to know.

Yeah, I know this is not an issue with this repo but still...

**Comment by JasonGT** [comment]
Hi Alex - I have no idea either. I did recently rebuild my machine, and was able to clone and run tests from scratch - no problems. Maybe a glitch in the matrix? :P
