### ISSUE TITLE
How to automatically, CQRS handler registration in ASP.NET Core ?

### ISSUE THREAD

**Issue by BionStt** [JasonGT/NorthwindTraders#132]
hii Jason,
Thank for this example architecture,
i have question, How to automatically register our handler in startup?

I read this article [https://dejanstojanovic.net/aspnet/2019/may/automatic-cqrs-handler-registration-in-aspnet-core-with-reflection/]
and follow his step. but I have not succeeded

result error:
`{"error":["Object reference not set to an instance of an object."],"stackTrace":"   at SmmCoreDDD2019Accounting.WebUI2.Controllers.DataPerusahaanController.CreateStructureOrganization() in C:\\Users\\Dermawan Gasali\\source\\repos\\SMMCodeDDD2019Accounting\\SmmCoreDDD2019Accounting.WebUI2\\Controllers\\DataPerusahaanController.cs:line 21\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()"}`

thanks

**Comment by BionStt** [comment]
i used this  `services.AddMediatR(typeof(Startup).GetTypeInfo().Assembly);' for manually register in startup.cs

**Comment by rafalschmidt97** [comment]
I really like [Scrutor](https://github.com/khellang/Scrutor) project. It's a simple extension for DI.

```c#
      var applicationAssembly = typeof(XYZClass).GetTypeInfo().Assembly;

      services.AddMediatR(applicationAssembly);
      services.Scan(scan =>
        scan.FromAssemblies(applicationAssembly)
          .AddClasses(classes => classes.AssignableTo(typeof(IPipelineBehavior<,>)))
          .AsImplementedInterfaces()
          .WithTransientLifetime());
```

**Comment by rafalschmidt97** [comment]
Wait wait... you don't need to do anything.

> If you're using ASP.NET Core then you can skip the above configuration and use MediatR's MediatR.Extensions.Microsoft.DependencyInjection package which includes a IServiceCollection.AddMediatR(Assembly) extension method, allowing you to register all Handlers and Pre/PostProcessors in a given assembly.

https://github.com/jbogard/MediatR/wiki#aspnet-core

**Comment by BionStt** [comment]
> Wait wait... you don't have to to do anything.
> 
> > If you're using ASP.NET Core then you can skip the above configuration and use MediatR's MediatR.Extensions.Microsoft.DependencyInjection package which includes a IServiceCollection.AddMediatR(Assembly) extension method, allowing you to register all Handlers and Pre/PostProcessors in a given assembly.
> 
> https://github.com/jbogard/MediatR/wiki#aspnet-core

yes thank you.

i solved this using `   var assembly = AppDomain.CurrentDomain.Load("SmmCoreDDD2019Accounting.Application");
            services.AddMediatR(assembly);`
