### ISSUE TITLE
We need example for CRUD operations

### ISSUE THREAD

**Issue by MohamedRagab10793** [JasonGT/NorthwindTraders#139]

**Comment by siriak** [comment]
What do you mean by CRUD operations? Is it controller actions or operations on DbContext?

**Comment by MohamedRagab10793** [comment]
example for consuming the api actions like create , update ,and delete

**Comment by siriak** [comment]
Hmm, I couldn't find any usage of create actions of api, though they are present in controller. It seems like they were not used at all. Anyway, you just need to call create(...) method on CustomersClient and pass in instance of CreateCustomerCommand.

**Comment by MohamedRagab10793** [comment]
please , can you explain complete  example for create action

**Comment by JasonGT** [comment]
Check out the customers controller; https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.WebUI/Controllers/CustomersController.cs.
