### ISSUE TITLE
CLI tool?

### ISSUE THREAD

**Issue by kmhigashioka** [JasonGT/NorthwindTraders#141]
Hi, first of all great architecture! I would just like to know if there is a plan to make a cli tool for generating this as template?

**Comment by JasonGT** [comment]
Hi Kazuhito. Thank you - that's a great idea, but not something I've capacity to include right now. If you would like to tackle it - let me know. :)

**Comment by kmhigashioka** [comment]
I definitely would love to contribute on this. Do you have any specific implementation in mind? :)
