### ISSUE TITLE
Implementing MassTransit

### ISSUE THREAD

**Issue by Mat2001mat** [JasonGT/NorthwindTraders#142]
Thanks for providing this project. I've learned a great deal from this and am trying to implement MassTransit in my application.

I'm struggling to work out how to place it. I've pushed it out towards the Infrastructure portion of the application. Which works absolutely fine for publishing/pushing events into my message queue. The problem I am facing though is how to deal with receiving/consuming events. I don't want to write my handlers for this down in the infrastructure layer and I'm not sure how to get it to call something like a mediator command or code in the application layer.

Would anybody be able to give me a pointer to help out?

**Comment by JasonGT** [comment]
Hi @Mat2001mat. Thanks for your question, this is not something I am looking to demonstrate in this solution, but it is certainly an interesting topic. You might find it useful to review https://github.com/dotnet-architecture/eShopOnContainers which includes an event bus. Happy coding!
