### ISSUE TITLE
[Question] Seeding IdentityUser entities, best approach ?

### ISSUE THREAD

**Issue by SonnyRR** [JasonGT/NorthwindTraders#145]
I have a ASP.NET Core MVC 2.2 project that I will be defending at the software academy I currently study at. Using this sample project and your presentation at NDC Conferences as a guide to CQRS and Mediator patterns, separation of concerns and working with higher abstraction levels I decided to use this approach because I liked it and found it fitting for my needs, also making it more distinctive than the others. 

My question is: I have scaffolded the default Microsoft.AspNetCore.Identity and also extended the default IdentityUser. What is the best approach to seeding an Administrator Role and root Administrator user ? The UserManager and RoleManager are very handy in the Presentation layer, but If I want to use them outside that means the Persistence layer will depend on the Presentation layer and I don't want that.

**Comment by JasonGT** [comment]
Good question. Follow this example; https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Identity/AppIdentityDbContextSeed.cs.

Think about what you need to do with UserManager and RoleManager. Then create an interface to support those methods. Add the interface to the Application layer. Now the business logic can use this interface. Next you will need to implement the interface. Ideally, you will do this in Infrastructure - this can be tricky. Suggest reviewing https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Identity in greater detail. 

Good luck!
