### ISSUE TITLE
Missing Node.js prerequisite in README.md

### ISSUE THREAD

**Issue by kaamil1984** [JasonGT/NorthwindTraders#146]
**Can you add links or some information about required version of Node.js please?**

I just tried to run this sample on my Debian server and looks like I have no Node.js installed.

In Debian repositories we have very old Nodejs version (4.x) and it doesn't work.

I had to uninstall it, and follow this article:
https://tecadmin.net/install-latest-nodejs-npm-on-debian/

Build succeded after I installed LTS version (10.x).

**Comment by JasonGT** [comment]
Thanks for raising this, I've updated the read me.
