### ISSUE TITLE
Authenticattion & Authorization (jwt)

### ISSUE THREAD

**Issue by amin-pi** [JasonGT/NorthwindTraders#150]
Please add jwt to this project
Or at least explain how it (jwt) is implemented in this structure.

thanks.

**Comment by rafalschmidt97** [comment]
https://github.com/JasonGT/NorthwindTraders/issues/107

**Comment by hesamkal2009** [comment]
@amin-pi Hi, check out my previous issue.
#136

**Comment by JasonGT** [comment]
Hi @amin-pi - thanks for the suggestion, I've got this covered in #92. Hope to get it in soon.
