### ISSUE TITLE
'ng' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by JohnGorman** [JasonGT/NorthwindTraders#151]
Hi Jason,

I seen your presentation of this on Youtube, seems great!  I'm having difficulties getting it working though.  Here is the log details:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle northwind.webui@0.0.0~prestart: northwind.webui@0.0.0
6 info lifecycle northwind.webui@0.0.0~start: northwind.webui@0.0.0
7 verbose lifecycle northwind.webui@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle northwind.webui@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\NorthwindTraders-master\Northwind.WebUI\ClientApp\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\john_\AppData\Local\Microsoft\WindowsApps;C:\Users\john_\.dotnet\tools;C:\Users\john_\AppData\Local\GitHubDesktop\bin;C:\Users\john_\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\john_\AppData\Roaming\npm;C:\Users\john_\AppData\Local\Microsoft\WindowsApps;C:\Users\john_\AppData\Roaming\npm\node_modules\@angular\cli\bin
9 verbose lifecycle northwind.webui@0.0.0~start: CWD: C:\NorthwindTraders-master\Northwind.WebUI\ClientApp
10 silly lifecycle northwind.webui@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
11 silly lifecycle northwind.webui@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle northwind.webui@0.0.0~start: Failed to exec start script
13 verbose stack Error: northwind.webui@0.0.0 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid northwind.webui@0.0.0
15 verbose cwd C:\NorthwindTraders-master\Northwind.WebUI\ClientApp
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error northwind.webui@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the northwind.webui@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any ideas?  I'm new to node and angular and a 'google' didn't help.

Thanks,
John

**Comment by JasonGT** [comment]
Hi John. Sorry it took so long getting back to you. Start by updating node / npm to the latest version - https://nodejs.org/en/. Node looks right, but npm should be at least on 6.9.0.

If ng, is not recognised - then that means that Angular CLI is missing. You can follow the steps here to install the latest version - https://cli.angular.io.

After that, try a fresh `npm install` from \Northwind.WebUI\ClientApp and then a dotnet run from \Northwind.WebUI.

Let me know how you go.
