### ISSUE TITLE
Should BaseController inherit from ControllerBase, not Controller?

### ISSUE THREAD

**Issue by ltjerry** [JasonGT/NorthwindTraders#157]
"Don't create a web API controller by deriving from the Controller class. Controller derives from ControllerBase and adds support for views, so it's for handling web pages, not web API requests. _There's an exception to this rule_: if you plan to use the same controller for both views and APIs, derive it from Controller."
[https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2](url)

**Comment by JasonGT** [comment]
Thanks @ltjerry, much appreciated - fixed.
