### ISSUE TITLE
What is this: Database=Microsoft.eShopOnContainers.Services.CatalogDb?

### ISSUE THREAD

**Issue by khaledelmahdi** [JasonGT/NorthwindTraders#158]
https://github.com/JasonGT/NorthwindTraders/blob/9d9a43c13a3700db1f9975ed0f3f067ffaef1865/docker-compose.override.yml#L9

**Comment by JasonGT** [comment]
Docker compose support added by @NicholasMead in #39.

**Comment by khaledelmahdi** [comment]
Thank you for your reply and sorry my question wasn't clear enough.

My question was: on the line I've attached ` - ConnectionStrings__NorthwindDatabase=Server=data.sql;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word` the database is `Microsoft.eShopOnContainers.Services.CatalogDb` 

Why we are referencing eShopOnContainers here?

**Comment by JasonGT** [comment]
No worries thanks for pointing that out. 

Assume that Nick based his implementation on the eShopOnContainers code found here; https://github.com/dotnet-architecture/eShopOnContainers. You can learn more about that here; https://dotnet.microsoft.com/learn/aspnet/microservices-architecture. It's a great solution.

It should have been changed before accepting the pull request. I've pushed through a fix now.
