### ISSUE TITLE
How to reference ASP.NET Core to Framework 4.7?

### ISSUE THREAD

**Issue by Ghislain1** [JasonGT/NorthwindTraders#16]
Hi @JasonGT,
Is it possible to use ASP.NET Core Web Api in a Framework Application?

I try to use Nuget Package  approch to reference  a ASP.NET Web Api to my Framework-App but it s not work.

Goal:
1. Create a WPF-Application which contains a Button  to start the desired ASP.NET Web Api 
2. Web Api uses single page app (Angular) to display  data-information.
3. WPF-Application contains a service which provides the desired data Information(Data-Source is WPF-APP)

I spent a lot of time  for this issue.!!

**Comment by JasonGT** [comment]
Hi @Ghislain1.

Yes, all of this is possible. References can be made between frameworks that support the relevant .NET Standard - see https://docs.microsoft.com/en-us/dotnet/standard/net-standard. 

Good luck.

**Comment by Ghislain1** [comment]
Hi JasonGT,
ASP.NET Web Api is .NetCore (see <TargetFramework>netcoreapp2.1</TargetFramework>)
Error occurs when i changed it to netstandard
Can you tell me how solve that issue?
Thank you
