### ISSUE TITLE
What if I have multiple applications using the same core?

### ISSUE THREAD

**Issue by alaminut** [JasonGT/NorthwindTraders#160]
Hi and thanks for sharing this code as well as presentation. It helped me to understand clean architecture.

I have one thing that haven't clicked yet though. My projects usually require a management panel (a CMS I dare to say) to implement CRUD operations. In Northwind Traders, products and other entities are seeded and there is no administration. CQRS components hence only tailored for UI needs.

Where do I put logic for a CMS / management panel in this case? Do I create different query / commands and handlers for CMS needs and maybe add an authorization pipeline to Mediatr? Would you change your folder structure if you had more than one UI client? (CMS is a UI client essentialy) How would you differentiate administration related CQRS components and others?

**Comment by JasonGT** [comment]
Hi @alaminut - thanks for your feedback. You can implement CRUD operations just fine within CQRS - take a look a customers and products. If you wanted to separate into difference subsets of commands / queries for the same application I'd probably just use a folder. I'd keep the same structure for supporting more than one UI client. However I might consider a separate API. It would depend on my specific needs. 

Keep in mind that the UI for Northwind is quite simple, I still need to add the ability to view, add, edit and delete entities - but that should be coming soon.

Hope this helps.
