### ISSUE TITLE
Commands as interfaces?

### ISSUE THREAD

**Issue by lucianoac** [JasonGT/NorthwindTraders#161]
I was wondering if abstracting commands as interfaces instead of classes would be usefull. Command handlers and Validators could be implemented against that interface.

Lets take an hypotetical ICreateProductCommand. This particular command could have different implementations: 

- CreateProductViewModel: ICreateProductCommand (for use with MVC View, could have some additional properties for View use only, like collections for dropdowns databinding)
- CreateProdutctDto: ICreateProductCommand (for use with a WebApi accessed by a mobile device, tailored for json serialization)
- CreateProductFromExcel: ICreateProductCommand (wich could be a form a batch writing, part of a totally different Product creation flow)

Is that make sense, or am I looking at it from a wrong perspective? Should I use composition instead (CreateProductViewModel have one CreateProductCommand ou returns a new CreateProductCommand instance)?

**Comment by brendan-ssw** [comment]
Hi Lucianoac,

Sure, a setup as you described could work well, but I personally think the setup in NorthwindTraders with Mediatr is clearer and let me explain why. 
We have a very clear distinction between defining the Command - which specifies the operation we want to invoke and contains all the data we need to make that invocation, and the CommandHandler which is the code that actually performs the work once we've passed in a Command instance.

I feel this distinction is less clear when interfaces define the command and implementations of that interface define the command handler. 

How would I handle the different kinds of differing use cases you provided?
For me the point of mediatr command/query specifications is that any code that is capable of building a command object can invoke that command - so I would make a CreateProductCommand that contains the common "save product" definition for all three use cases and then get the various paths to build that from their respective WebAPI or MVC controllers etc.
If there is lookup data needed to populate dropdowns etc, I would make that a separate Query.

**Comment by lucianoac** [comment]
Hi Brendan,

thanks for your feedback. I find software architecture a fascinating topic and it's very nice to talk about it with someone experienced like yourself. Awesome project by the way! Keep going.

**Comment by JasonGT** [comment]
Keep it simple, each command or query represents a single and separate business use case. If there is duplication of logic, push it down. Refer to Jimmy's article [Dealing with Duplication in MediatR Handlers
](https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/). Happy coding!
