### ISSUE TITLE
Package restore failed. Rolling back package changes for 'Northwind.UI'.				

### ISSUE THREAD

**Issue by zdrave08** [JasonGT/NorthwindTraders#162]
When I add into project throw refrencies I get this error.

> Error	NU1107	Version conflict detected for Microsoft.EntityFrameworkCore. Install/reference Microsoft.EntityFrameworkCore 2.2.3 directly to the project Northwind.UI to resolve this issue. 
>  Northwind.UI -> Northwind.Persistence -> Microsoft.EntityFrameworkCore.SqlServer 2.2.3 -> Microsoft.EntityFrameworkCore.Relational 2.2.3 -> Microsoft.EntityFrameworkCore (>= 2.2.3) 
>  Northwind.UI -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.EntityFrameworkCore (>= 2.1.1 && < 2.2.0).	Northwind.UI

	

Also when I pull the app from github and run command **dotnet restore** the same error occurs.

Thanks

**Comment by rasmuseeg** [comment]
Hi there,

Right click the solution and click manage solution packages, the open the consolidate tab, and find the package which has version conflict.

Best regards

**Comment by JasonGT** [comment]
Assuming this has been resolved, if not - let me know.
