### ISSUE TITLE
How to support domain event

### ISSUE THREAD

**Issue by kuacci** [JasonGT/NorthwindTraders#163]
Hi

I want to include domain events in my project, but not sure where should I put it? Domain layer or Application layer?

Also the most common way to construct domain events is event bus with publisher/subscriber pattern, then event consumer/handler should be aware of some information from event publisher. So my question is that how we wrap these information and expose to consumer/handler, by DTO in application layer?

Thanks,

**Comment by JasonGT** [comment]
This would make a good example for Northwind. In short, my recommendations are as follows:

1. Publish events to the event bus from commands. You can do this directly, say through an IEventBus interface or by using MediatR (see [Publishing](https://github.com/jbogard/MediatR/wiki#publishing)).
2. Subscribe to events in the API, with events received triggering corresponding commands.

In this way the information flows normally. Hope this helps.
