### ISSUE TITLE
IMapTo<> not working properly

### ISSUE THREAD

**Issue by Pyrobolser** [JasonGT/NorthwindTraders#164]
Hi,

I am wondering how is IMapTo<> supposed to work?
I don't see anything in [here](https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.Application/Infrastructure/AutoMapper/MapperProfileHelper.cs), I suppose you forgot about it because you don't use it anywhere or I am mistaken and I am missing something?

Maybe it is [already planned following this question](https://github.com/JasonGT/NorthwindTraders/issues/90) a while back.

Thank you!

**Comment by JasonGT** [comment]
You're absolutely right - it's not working correctly. I want to rework the AutoMapper implementation to use the ProjectTo feature - [AutoMapper LINQ Support Deep Dive](https://jimmybogard.com/automapper-linq-support-deep-dive/). This is the best approach - maybe you will find it useful. 

There is a task on the roadmap to complete this work; https://github.com/JasonGT/NorthwindTraders/projects/1#card-19794042. It should be completed by the time .NET Core 3 is released.

Thanks for your feedback.
