### ISSUE TITLE
Throwing Exception in validation flow

### ISSUE THREAD

**Issue by A-Soltani** [JasonGT/NorthwindTraders#166]
Hello, I inspect the repository and I got an issue about the validation way in the application layer. 
According to following link, there is a [RequestValidationBehavior ](https://github.com/JasonGT/NorthwindTraders/blob/c942193b02762561968c3981d9172e6e6fc6d274/Northwind.Application/Infrastructure/RequestValidationBehavior.cs#L33)to validate input data by using `FluentValidation` that is similar to [ValidatorBehavior](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/ValidatorBehavior.cs) in [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers). One of the issue is throwing exception in the code below.
https://github.com/JasonGT/NorthwindTraders/blob/c942193b02762561968c3981d9172e6e6fc6d274/Northwind.Application/Infrastructure/RequestValidationBehavior.cs#L33

I like `ValidatorBehavior` that [MediatR ](https://github.com/jbogard/MediatR/wiki) have provided for us, but if throwing exception is used in handling validation there could be a big problem by using it. The problem is controlling the flow of business by exceptions that is wrong. I have thought about modifying this line of code to avoid throwing exception, but I couldn't come up with an idea.

**Comment by JasonGT** [comment]
Hi @A-Soltani - thanks for your feedback. I think about this approach sometimes too. Perhaps a better approach would be to use a RequestResult<T>. This could include properties such as Succeeded (was the request successful) and Errors[] (if not successful, what were the errors).

In this way, we have a consistent approach to return results, errors or otherwise.

What do you think - do you like this approach better? 

Feedback from everyone else welcome.

**Comment by JasonGT** [comment]
As an example:

```csharp
    public class RequestResult<T>
    {
        public bool Succeeded { get; set; }

        public IEnumerable<RequestError> Errors { get; set; }

        public T Result { get; set; }
    }

    public class RequestError
    {
        public string Code { get; set; }

        public string Description { get; set; }
    }

    public class GetCustomerDetailQuery : IRequest<RequestResult<CustomerDetailVm>>
    {
        public string Id { get; set; }
    }
```

The problem with this approach, is that the RequestError is quite generic in nature. An error type might be required to differentiate between authorisation, validation, not found and so on. Different types will be handled differently by an API client, 401, 400, 404, etc.

Thoughts?

**Comment by JasonGT** [comment]
Just reviewing eShopOnContainers, and they take the same ValidationException approach:

```csharp
if (failures.Any())
{
    _logger.LogWarning("Validation errors - {CommandType} - Command: {@Command} - Errors: {@ValidationErrors}", typeName, request, failures);

    throw new OrderingDomainException($"Command Validation Errors for type {typeof(TRequest).Name}", 
        new ValidationException("Validation exception", failures));
}
```

The goal should be to find the simplest approach. In this case, we could state that the initial responsibility is with the client to validate the request. If the client fails to do so, then this is an exceptional circumstance - hence the ValidationException is thrown. This is therefore the simplest approach.

Thoughts?

**Comment by JasonGT** [comment]
No feedback so I am going to close this issue.

If you're interested in an alternative approach take a look at the new implementation for the UserManagerService which returns a Result type; https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Infrastructure/Identity/UserManagerService.cs
