### ISSUE TITLE
[Question] User entity seeding

### ISSUE THREAD

**Issue by cookiebutcher** [JasonGT/NorthwindTraders#17]
Hi,
is there a nice way to create a seeder to the User entities? 
I mean using HasData() method.
When I try to do it I keep getting error that "The seed entity for entity type 'User' cannot be added because it has the navigation set."

**Comment by JasonGT** [comment]
Hi @cookiebutcher,

In this particular solution I am just using a generic NorthwindInitializer (see https://github.com/JasonGT/NorthwindTraders/tree/master/Northwind.Persistence). 

Alternatively, Check out this article to learn more about HasData() - https://msdn.microsoft.com/en-us/magazine/mt829703.aspx.

Good luck.
