### ISSUE TITLE
Can someon explain the point of this test?  

### ISSUE THREAD

**Issue by punkouter2018** [JasonGT/NorthwindTraders#171]
As I interpret it.. 

Its to verify that it raises some sort of event... Which event is it checking if it raised ? And how do you explain this line ?  

            mediatorMock.Verify(m => m.Publish(It.Is<CustomerCreated>(cc => cc.CustomerId == newCustomerId), It.IsAny<CancellationToken>()), Times.Once);

Is is verifying the same Id was passed and what is happening Times.Once?  ..

And what does the cancellationToken have to do with it ?

I am using the test but I want to understand better what is going on and why this test would be helpful.

`     public void Handle_GivenValidRequest_ShouldRaiseCustomerCreatedNotification()
        {
            // Arrange
            var mediatorMock = new Mock<IMediator>();
            var sut = new CreateCustomerCommand.Handler(_context, mediatorMock.Object);
            var newCustomerId = "QAZQ1";

            // Act
            var result = sut.Handle(new CreateCustomerCommand { Id = newCustomerId }, CancellationToken.None);

            // Assert
            mediatorMock.Verify(m => m.Publish(It.Is<CustomerCreated>(cc => cc.CustomerId == newCustomerId), It.IsAny<CancellationToken>()), Times.Once);
        }`

**Comment by DrBarnabus** [comment]
Basically, it is verifying that Publish has been called once with the correct CustomerId and any valid Cancellation Token (the Cancellation Token is only there so it matches the function signature of Publish, which is a requirement for the Mock).

With this you can verify that the notification was created and was published the correct number of times and could help catch an error if someone for example removed the Publish call from the CommandHandler.

**Comment by JasonGT** [comment]
Just as @DrBarnabus has said - the event should be raised. If the command is changed such that the event isn't raised, the test should fail. We want to protect this behaviour.
