### ISSUE TITLE
Query with Include - child table

### ISSUE THREAD

**Issue by sudurrani** [JasonGT/NorthwindTraders#175]
I have two tables Parent and Child want to get data from parent to child using .Include, issue is how can we configure map for it. below is the query
```
var tenantUsers = await _context.Tenants.Where(tenant => tenant.TenantId == request.TenantId)
                 .Include(user => user.Users)
                 .ProjectTo<UsersListVM>(_mapper.ConfigurationProvider)                 
                 .FirstOrDefaultAsync(cancellationToken)                 
                 ;
```

**Comment by JasonGT** [comment]
Hi Shahid - I've added an example here - https://github.com/JasonGT/NorthwindTraders/tree/master/Src/Application/Employees/Queries/GetEmployeeDetail. 

Thanks for the question. :)

**Comment by JasonGT** [comment]
Hope the example helped, closing this issue.

**Comment by sudurrani** [comment]
> Hope the example helped, closing this issue.

Thanks, solved my issue
