### ISSUE TITLE
Duplicated logic in CustomerCommandValidator

### ISSUE THREAD

**Issue by klepersontimur** [JasonGT/NorthwindTraders#180]
You have duplicate validation logic in the Create and Update Customer commands. What do you think, how to solve this problem elegantly? What about checking in the database in the same validator instead of command? 

For example:
```
 public class CreateBankValidator : AbstractValidator<CreateBankCommand>
    {
        public CreateBankValidator(IDbContext dbContext, ILocalizationService localizationService)
        {
            RuleFor(p => p.Name).NotEmpty();
            RuleFor(p => p.UniqueIdentifier).NotEmpty().MustAsync(async (request, ct, context) =>
            {
                var bankWithUniqIdent = await dbContext.Set<Bank>().FirstOrDefaultAsync(p => p.UniqueIdentifier == request.UniqueIdentifier);
                if (bankWithUniqIdent != null)
                {
                    return false;
                }
                return true;
            }).WithMessage(localizationService.GetResource("Api.Parties.Bank.Fields.UniqueIdentifier.MustBeUniq"));
            
        }

    }
```

**Comment by JasonGT** [comment]
In this case we could simply merge Create and Update into a single Upsert command. I've done that in a few of the recent additions such as:
- https://github.com/JasonGT/NorthwindTraders/tree/master/Src/Application/Categories/Commands/UpsertCategory

The alternative would be to move the validation logic to domain layer, however I'd be hesitant to add any frameworks at that layer. 

I'm actually not that phased by having some duplicated validation. There are benefits - for example, the create and update validation can change independently, without the chance to introduce side effects. This is useful when validation rules are different for creating and updating.

 What do you think?

**Comment by klepersontimur** [comment]
I wouldn't either move validation logic to domain layer.

UpsertCategory - good idea, but IMHO it works only for same commands, without difirent logic on create and update operations.

> I'm actually not that phased by having some duplicated validation. There are benefits - for example, the create and update validation can change independently, without the chance to introduce side effects. This is useful when validation rules are different for creating and updating.

I agree with you. It will take some benefits - flexible and independence.. But what about principle - don't repeat to yourself? It's confusing me. if we will add some fields in domain model class, we will need implement two validator logic. For example: if we have domain model with 10 properties and same validation for 7 properties on create and update operations we need implement this validation rules on both validators.

**Comment by JasonGT** [comment]
The principal DRY, or Don't Repeat Yourself states that "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system". In this case I consider the knowledge associated with the Create Customer command, to be separate from the knowledge associated with the Update Customer Command. So by this logic, I am not violating DRY. The two separate pieces of knowledge represent two independent business use cases.

So yes, if we update a related domain entity, we will need to update the validation rules in multiple places. In this case create and update. Being that the domain entities are at the lowest levels of our system, these cascading changes are kind of expected.

Some additional thoughts in a blog post here; https://lostechies.com/jimmybogard/2016/04/29/validation-inside-or-outside-entities/.

**Comment by klepersontimur** [comment]
Thank. everything is clear and understandable. I agree with you! Thanks for your project. I wish you good luck in your development.
