### ISSUE TITLE
How interface can have declared body ?

### ISSUE THREAD

**Issue by danijel88** [JasonGT/NorthwindTraders#183]
public interface IMapFrom<T>
    {   
        void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType());
    }

**Comment by JasonGT** [comment]
This is my favourite new thing, it worked really well for what I was trying to accomplish with AutoMapper.

Beginning with C# 8.0 on .NET Core 3.0, you can define an implementation when you declare a member of an interface. Learn more here; https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-members-versions.

In this case it means I can add IMapFrom<NameOfDto> to any DTO and it will automatically be registered with AutoMapper for mapping. If the mapping is completely conventions based, I don't need to do anything else other than add the interface.
