### ISSUE TITLE
 Project folders with different .net framework

### ISSUE THREAD

**Issue by rrodriguezreyes** [JasonGT/NorthwindTraders#189]
Why do the projects within the core folder all point to the .net standard framework 2 ? The other project folders to .net core 3, I am using the project from a mac and I saw that problem for me.

![image](https://user-images.githubusercontent.com/39017677/66710466-1e666a00-ed47-11e9-86f7-7ca2d49ae7e4.png)

![image](https://user-images.githubusercontent.com/39017677/66710473-4655cd80-ed47-11e9-979f-8f846cdabefe.png)

**Comment by brendan-ssw** [comment]
Hi rrodriguezreyes,

The projects core are libraries and are netstandard 2.1 to make them more widely compatible for use from any other startup project.

Projects used to start the application (such as the WebUI) need to specify a full runtime (.Net core 3.0)  

As for the Persistence project, well that is a library, but if we made this netstandard, we would not be able to invoke ef core migrations directly against that project, we would have to use the -s switch for "dotnet ef migrations add" to specify a startup project. 
We found it easier to just make the project containing the migrations directly reference a target framework so you can work on the data migrations independently from the WebUI project.

If you don't like this and want to make the infrastructure webstandard you can either:
- use the webui project as your startup
- add a small console project to use to bootstrap the ef core migration independently from tthe WebUI project.

**Comment by rrodriguezreyes** [comment]
I understand that in that way it can be useful for migrations, I just had to adjust some things from visual studio to mac because I am using postgresql
 
Thank you
