### ISSUE TITLE
How to add migrations on infrastructure?

### ISSUE THREAD

**Issue by rasmuseeg** [JasonGT/NorthwindTraders#191]
Hi Jason,

Thanks for inspiring us to write learner code.

I've set up a project based on this structure, and was able to add migrations to `Persistence` by running `dotnet ef migrations add CreateCustomSchema` which is working great with the design time pattern. 

But i'm not able to add migrations to `Infrastructure` the same way like so 
```
dotnet ef migrations add CreateIdentitySchema
```

I can't see that there has been implemented any design time pattern in the `Infrastructure` project. And have not been able to find any documentation on how to create schema for ApiAuthenticationDbContext implementation.

Can you help point to relevant sources?

Best Regards 
Rasmus

PS: The custom project lives here: https://github.com/bitflipping-net/doctrina-lrs

**Comment by Mat2001mat** [comment]
Something like this? dotnet ef migrations add init --project ../pathtoinfrastructureproject.csproj --context ApplicationDBContex

**Comment by rasmuseeg** [comment]
Hi @Mat2001mat thanks for responding.
So i tried your suggestion, and that gives the following response:
```
PS C:\Repos\BitFlipping\Doctrina\src> dotnet ef migrations add CreateIdentitySchema --project .\Doctrina.Infrastructure\ --context DoctrinaAuthorizationDbContext -s .\Doctrina.WebUI\
An unexpected return type was encountered while accessing the Microsoft.Extensions.Hosting services. Method 'CreateHostBuilder(string[])' should return an object of type 'IHostBuilder'. Continuing without the application service provider.
Unable to create an object of type 'DoctrinaAuthorizat
```

And here i try one where i specify the `--startup [-s]` for startup project from within infrastructure.
```
PS C:\Repos\BitFlipping\Doctrina\src\Doctrina.Infrastructure> dotnet ef migrations add CreateIdentitySchema -s ..\Doctrina.WebUI\
An unexpected return type was encountered while accessing the Microsoft.Extensions.Hosting services. Method 'CreateHostBuilder(string[])' should return an object of type 'IHostBuilder'. Continuing without the application service provider.
Unable to create an object of type 'DoctrinaAuthorizationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

Any further suggestions? 👍
