### ISSUE TITLE
How to return Default/Identical Response from API 

### ISSUE THREAD

**Issue by majumajid** [JasonGT/NorthwindTraders#192]
How to return Default Response from API 
example :

public class ResultBase
{
public bool Success {get;set;}
public T ResultData {get;set;}
}

All the Request which come to system should response in identical format .
how to implement this in NorthwindTrader concept ?

**Comment by majumajid** [comment]
@JasonGT  Kindly provide reply

**Comment by Patrick-Ullrich** [comment]
@majumajid , this question might be out of scope for this project. 

You probably want some sort of middleware that wraps your response. A quick google brought me to this [SO post](https://stackoverflow.com/questions/40748900/how-can-i-wrap-web-api-responsesin-net-core-for-consistency)

Alternatively you could write yourself a little helper method that takes T and returns a ResultBase which you can call from your controllers.

**Comment by majumajid** [comment]
@Patrick-Ullrich  Noted.
