### ISSUE TITLE
Where should i put if i have multiple presentation layer ? 

### ISSUE THREAD

**Issue by majumajid** [JasonGT/NorthwindTraders#200]
For Example : 

I have 3  layer Presentation 

One is API thats using by Mobile App, Another API thats for admin website , another API for reporting for customer . 
In this case ,
Where should i keep logic   ? 
If i have controller and functions that used by API( which consumed by MobileApp) , Where should i keep this business logic ? 

If any functions required  to use in 2 of API , I think its better to keep that business logic in Application Layer  and from both controller mediator will call it , 

Kindly anyone help to solve and guide me best . 
@JasonGT Thank you so much for your great project .

**Comment by NerijusD** [comment]
@majumajid I would advice to keep your API gateway consistent for all 3 of your consumers `mobile app` `admin dashboard` `customer reports`

Use authentication and authorization to control which part of your API can be accessed, probably admins have full rights to access all endpoints, while customer have only publicly opened API endpoints, while mobile might have some public and private requiring authentication and maybe authorization?

**Comment by majumajid** [comment]
@NerijusD Thank you for answer.

My Question is about keeping business logic of the system in application layer or api ?

If any functions required to use in 2 of API , I think its better to keep that business logic in Application Layer and from both controller mediator will call it ,

I have one system database ex:  abcdDb 
i have one identity Db : abcdIdentityDb

i have 3 API . 
1 is consumed by Mobile App -
1 is consumed by Customer Reporting/Product Modification  - Angular8 web
1 is consumed by Administration of mobile App . - Angular8 web


As you said, i have public api for customer which use jwt token and admin use  jwt token.
api for mobile app, which have some more authenticaiton apart from jwt.


I have some case, like some mobile api specific logic neeed to call from MobileApp API and web AdminAPI.

Should i keep my that logics in application layer ? if logic for mobileapp only,can i put in MobileAppAPI

**Comment by majumajid** [comment]
Anyone else have any suggestions ?

**Comment by majumajid** [comment]
Since no reply, closing this issue.
Thank you @JasonGT for great Repo
