### ISSUE TITLE
Start port is 4200

### ISSUE THREAD

**Issue by MasterOM** [JasonGT/NorthwindTraders#21]
To run webclient use http://localhost:4200 path, not "Launch http://localhost:52468/ in your browser to view the Web UI" - as described at 6th step, otherwise you'll be getting error : 

An unhandled exception occurred while processing the request.
SocketException: No connection could be made because the target machine actively refused it
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

HttpRequestException: No connection could be made because the target machine actively refused it
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

HttpRequestException: Failed to proxy the request to http://localhost:4200/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:4200/.

The underlying exception message was 'No connection could be made because the target machine actively refused it'.Check the InnerException for more details.
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task<Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)

**Comment by JasonGT** [comment]
Hi @MasterOM, you need to launch the frontend first:

1. Change to the Northwind.WebUI\ClientApp directory
2. Execute the following command:
```
npm start
```

Check out the [readme](https://github.com/JasonGT/NorthwindTraders/blob/master/ReadMe.md) for additional information, let me know if you get stuck.

**Comment by yarrgh** [comment]
The API will try to proxy the request to port 4200.
https://github.com/JasonGT/NorthwindTraders/blob/ed444622298bcef603bbf42a3385f02a271aa2e4/Northwind.WebUI/Startup.cs#L107

Like @JasonGT said, first start the ClientApp (via `npm start`) then launch the API. Now when you to go http://localhost:52468 you'll see the ClientApp

**Comment by MasterOM** [comment]
@yarrgh @JasonGT Guys, thanks for responses. Application successfully was ran. 
When trying to run it, sure I ran 'npm start' and 'dot net run' all the times (but thanks for reminding), but it seems that yesterday .net core didn't run correctly (I don't know another reason), and that's why port 52468 did'nt respond as expected, but 4200 woked good. 
The issue may be closed.
Thanks.

**Comment by eduaalexandre** [comment]
Adding the first line command on the Startup.cs class, the my problem was resolved:

`                    spa.UseAngularCliServer(npmScript: "start");
                    spa.UseProxyToSpaDevelopmentServer("http://localhost:42000/"); `

**Comment by yakupcanatalar** [comment]
When I added spa.UseAngularCliServer(npmScript: "start"); in startup.cs my problem is solved.
Thanks for all comments
