### ISSUE TITLE
Guidance On IIS deployment

### ISSUE THREAD

**Issue by SuliemanMansouri** [JasonGT/NorthwindTraders#212]
Hi
I have been trying to host a sample application based on clean architechture template, on windows 10 IIS server.
I have followed the instructions provided in [Here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0) and [Here](https://jakeydocs.readthedocs.io/en/latest/publishing/web-publishing-vs.html) to no avail.
I have added this line: 
```
 services.Configure<IISOptions>(options =>
            {
                options.AutomaticAuthentication = false;
            });
```
to Startup.cs
and changed Program.cs host initialization to:
```
var host = new WebHostBuilder()
        .UseKestrel()
             .UseContentRoot(Directory.GetCurrentDirectory())
             .UseIISIntegration()
             .UseStartup<Startup>()
             .Build();
```
this [article](https://www.c-sharpcorner.com/article/iis-how-to-host-a-net-core-application-in-10-steps/) suggested adding a web.config to my project in order to properly deploy .net core to iis.

all my attempts result in error:

**HTTP Error 500.19 - Internal Server Error**
**The requested page cannot be accessed because the related configuration data for the page is invalid.**

Is it possible to deploy the clean architecture template to IIS? what are my options here? I need someone to point me to the right direction.
thanks

**Comment by ClassTerr** [comment]
I recently faced with this issue - you simply need to Install the .NET Core Hosting Bundle: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0

**Comment by SuliemanMansouri** [comment]
Thanks @ClassTerr  for the reply.
I installed the hosting bundle, the error changed to 500.30.
after checking windows error log. I found that I can't create a database using localdb access is denied. So I changed my connection string to use sqlexpress instead. now in the error log here is the new message
fail: xxx.WebUI.Program[0]
      An error occurred while migrating or seeding the database.
Microsoft.Data.SqlClient.SqlException (0x80131904): CREATE DATABASE permission denied in database 'master'.
even creating the database using update-database in visual studio and restarting the page in IIS. I still get the same error

**Comment by ClassTerr** [comment]
@SuliemanMansouri there is possible solutions:
1) To create a new user at sqlexpress (or use existing) and grant full access for this user. Then add credentials of this user to connection string.
2) Install localDb: 
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15
Then check localdb status by cmd command: 
SqlLocalDB.exe info
Should output MSSQLLocalDB

Good luck

**Comment by SuliemanMansouri** [comment]
I went with a different approach, I changed the identity for the application pool to use my current logged in account. The database was created but I am having problem with aspnetcore identity user manager
error message:
warn: Microsoft.AspNetCore.Identity.UserManager[14]
      User 60de11e3-ccb0-468b-b2a1-a963d3a11512 password validation failed: PasswordTooShort;PasswordRequiresDigit;PasswordRequiresUpper.

fixed the error by specifying a complex password in the seed method. Still no joy, now it complains that key type not specified.

**Application '/LM/W3SVC/2/ROOT' with physical root 'D:\myApp\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Application startup exception: System.InvalidOperationException: Key type not specified.
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.LoadKey()
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.Configure(ApiAuthorizationOptions options)**

**Comment by SuliemanMansouri** [comment]
Hi @ClassTerr 
I narrowed it down to a certificate problem. I need to create a certificate and change my settings to include the certificate.
I created a certificate in IIS and changed the settings to 
```
"IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=myApp"
    }
  }
```
now the error is 
**Application startup exception: System.InvalidOperationException: Couldn't find a valid certificate with subject 'CN=myApp' on the 'CurrentUser\My'**

I followed this [article](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#deploy-to-production) but there is no mention on how to create a certificate and where to store it so the above code would work.

I am still on this problem until I solve it, then I'll try to include the whole procedure in the wiki for future reference.

**Comment by SuliemanMansouri** [comment]
Here is what I got so far in deploying the sample application using clean-architecture template:

1. I created a new project using the ca-sln template. 
2. changed the seeding method to include a complex password.
3. published to a directory using Visual Studio publish.
4. added website in IIS with port 8034.
5. changed the application pool identity to my user account with my password.
6. Created a certificate in IIS. 
7. Exported the certificate and placed it in web root folder.
8. changed the configuration to the following 

```
"IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=CertificateName"
    }
  }
```
restarted my website in IIS.

Now the first page displays with errors
```
main-es2015.2fc22897ed571398a24f.js:1 ERROR Error: Uncaught (in promise): Error: Could not load settings for 'xxx.WebUI'
Error: Could not load settings for 'xxx.WebUI'
```
from the error message I have a problem with the settings for my website.
if anyone can point me to the right direction I would appreciate the help
thanks

**Comment by ClassTerr** [comment]
@SuliemanMansouri probably, you need to install dependencies for frontend (error in javascript file). So, you have to run the next command:
`npm install`
from NorthwindTraders/Src/WebUI/ClientApp folder

**Comment by SuliemanMansouri** [comment]
@ClassTerr I am trying to deploy to IIS in my dev machine so node is installed.
I can access home, counter, register and login pages. but after logging in my name is not displayed in the navigation. 
The Todo and Fetch data doesn't display at all.

**Comment by SuliemanMansouri** [comment]
here is what I had to change to solve this. I changed my appsettings.json to the following 
```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=.\\SQLEXPRESS;Database=EMenu;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
  "IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=Tardis"
    },
    "Clients": {
      "xxx.WebUI": {
        "Profile": "IdentityServerSPA"
      }
    }
  },
"AllowedHosts": "*"
}
```
