### ISSUE TITLE
[Question] How would I go about to set up docker for this kind of application

### ISSUE THREAD

**Issue by mikevanl** [JasonGT/NorthwindTraders#228]
I'm currently struggling to get a docker-compose file together that would run the back-end, front-end, and the database in a docker container. Is there anyone who could direct me to an example of how to go about this for this example project?

**Comment by tutul2010** [comment]
Same qtns , i have also..
Thanks @mikevanl.

Regards,
Tutul

**Comment by zePanzerfaust** [comment]
When they used dotnet 2.2 there were docker files. Probably got removed after a bigger refactoring and upgrade to 3.x.
Go back in the sources to commit 62c198a38b89a13b1557c3352156b7d915991bac
or
https://github.com/JasonGT/NorthwindTraders/pull/39
Maybe it helps as a starting point.

**Comment by mikevanl** [comment]
Thank you @zePanzerfaust for giving directions!
