### ISSUE TITLE
[Question] Authorization resources

### ISSUE THREAD

**Issue by Sp-NNT** [JasonGT/NorthwindTraders#29]
Hi,

firstly, thank you for this great sample app. I have used the app as template for my 2 projects. And it really helped me.

I placed authentication in the presentation layer. In StartUp class I added authentication service(Jwt) and used Authorize attributes in controllers. But I had problems with authorization of resources. For instance, one author cannot view papers of another author, therefore I had to add additional fields to queries like UserId to recognize who ask the paper, and if User was author, I allowed to give a resource, otherwise returned Forbid().

1. Do you plan to implement authentication/authorization?
2. Thirdly, how would you solve my problem?

Thanks a lot for any response! Good luck!

**Comment by Advanium** [comment]
On [YouTube](https://www.youtube.com/watch?v=_lwCVE_XgqI&lc=UgyP2iYTjMhbtNWgR1F4AaABAg.8mob_ODVO2W8mqU0lPm6Xl) he said he will be trying to add authentication (and authorization) later on and brought up some useful links. Have a look.

**Comment by JasonGT** [comment]
> Thanks for the feedback! I will try to add authentication / authorisation to the solution in the coming weeks. In the meantime, take a look at this sample as it includes integration with ASP.NET Core Identity - https://github.com/dotnet-architecture/eShopOnWeb. If you're building single page apps, you might like to look at this post also - http://jasonwatmore.com/post/2018/06/26/aspnet-core-21-simple-api-for-authentication-registration-and-user-management.﻿

> One approach would be to add an interface to the Application layer with the relevant members (LogIn, LogOut, IsInRole, CurrentUser, ...), implement the interface within the Infrastructure layer using your preferred framework, e.g. ASP.NET Core Identity.﻿

As per YouTube comments. :)

**Comment by Sp-NNT** [comment]
Thank you for taking the time to share all of that great information with me

**Comment by CodeRapp3r** [comment]
1)Please Make Identity server as separate solution
2)Please Add User Seeder Class
Can i use Dappper instead of identity  Entity Framework

**Comment by rafalschmidt97** [comment]
> 1)Please Make Identity server as separate solution
> 2)Please Add User Seeder Class
> Can i use Dappper instead of identity Entity Framework

Dapper - for now his application layer use dbcontext directly so in case of using dapper you are forced use something like unit of work or pass dapper everywhere (which is terrible idea).But with ef adding extra layer for db is useless I think because as he said on presentation ef is already well abstracted and you can change mssql to postgre with one package replacement.
