### ISSUE TITLE
Clean Architecture and Core Identity

### ISSUE THREAD

**Issue by NihadOb** [JasonGT/NorthwindTraders#33]
Any advice how to implement core Identity and still keep Clean Architecture?

**Comment by Morreed** [comment]
I would separate out new infrastructure project containing only identity, with it's own DbContext (you can use separate database, but contexts can share db so I wouldn't fuss about it at this scale). Preferably you would authorize on controller methods, therefore removing any dependency from your actual application. By using policies you can then further encapsulate "business logic" concerning auth rights if need be.

**Comment by JasonGT** [comment]
Be sure to check out https://github.com/dotnet-architecture/eShopOnWeb. It implements as described above. I'll try to add to this solution in the coming weeks.
