### ISSUE TITLE
Different HTTP statuses, domain related validation, domain related handling.

### ISSUE THREAD

**Issue by tautvydasversockas** [JasonGT/NorthwindTraders#35]
Hi,

First of all, thank You for such a nice code example. I do really like this architecture and will try to use it in the nearly future. However, I still have some questions.

1. How do You handle different HTTP response codes? I.e. what if I wrote a REST api and decided to use codes like 201, etc. It seems like You almost always return 200 on success.

2. Is this the "Vertical slice" architecture which is being promoted in various conferences by Jimmy Bogard? 

3. Where do You put your domain/persistence validation (since You seem to be only validating user inputs)? In https://github.com/jbogard/ContosoUniversityCore Jimmy Bogard moves it into the domain model.

4. Does all of your domain/application logic go to handler? In https://github.com/jbogard/ContosoUniversityCore Jimmy Bogard takes domain handling logic, puts it into the domain model and calls it from the handler. 

What are Your thoughts on these questions?

**Comment by JasonGT** [comment]
Hi and you're welcome. Sorry it took me so long to get back to you. Please see my responses below:

> 1. How do You handle different HTTP response codes? I.e. what if I wrote a REST api and decided to use codes like 201, etc. It seems like You almost always return 200 on success.

It's no problem to return different codes. Nothing in this design will get in your way. You should check out the improvements in ASP.NET Core 2.2 for Open API analysers and conventions. Very helpful stuff. https://blogs.msdn.microsoft.com/webdev/2018/08/23/asp-net-core-2-20-preview1-open-api-analyzers-conventions/?WT.mc_id=-blog-scottha

> 2. Is this the "Vertical slice" architecture which is being promoted in various conferences by Jimmy Bogard?

Not specifically. Although I did learn alot from his work.

> 3. Where do You put your domain/persistence validation (since You seem to be only validating user inputs)? In https://github.com/jbogard/ContosoUniversityCore Jimmy Bogard moves it into the domain model.

In this solution I am validation the commands and queries. Validation or shared logic specific to the domain can be pushed down to the domain as per Jimmy's work.

> 4. Does all of your domain/application logic go to handler? In https://github.com/jbogard/ContosoUniversityCore Jimmy Bogard takes domain handling logic, puts it into the domain model and calls it from the handler.

Suggest that any shared logic get pushed down from the handlers to the domain.

Hope this helps, all the best.

**Comment by tautvydasversockas** [comment]
Thank you very much!
