### ISSUE TITLE
Cannot create instance of an interface

### ISSUE THREAD

**Issue by Ashwani44** [JasonGT/NorthwindTraders#40]
Hi Jason , I really appreciate for your contribution . I have just step up my project as per your guidance but when i am adding the migration its showing me error "**Cannot create instance of an interface**" . I am not having any other interface in my project except this **IDesignTimeDbContextFactory** i am getting exception of this interface.  Also i would like to know what this file really does in persistance layer "NorthwindInitializer.cs" . I did not created this file in my persistance layer. Does this file absence creating issue for me ? Pls check this file. 
I am using core 2.1 
[ef error.txt](https://github.com/JasonGT/NorthwindTraders/files/2612857/ef.error.txt)

**Comment by eb-clickfusion** [comment]
Check out the NorthwindDbContextFactory and the DesignTimeDbContextFactoryBase classes in the Persistence layer.

The NorthwindInitializer class seeds the database. See here for more details: [https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)

**Comment by Ashwani44** [comment]
Its working now.
Thanks

**Comment by Ashwani44** [comment]
Hi Jason , its really frustating i don't know where i am going wrong. 
I was making a small demo today and i end up with the same above issue " **cannot create instance of an interface**". 
Is this a version issue ? I am using .net standard class
 library instead of .netcore library .
Does this causing me the issue ? Or am i doing something really wrong .
Please check this [doubt ef core.txt](https://github.com/JasonGT/NorthwindTraders/files/2640870/doubt.ef.core.txt)
Please help me out .
Thanks

**Comment by lukehammer** [comment]
Ashwani44  if you could post the repo. I'll take a look this evening.  I been meaning to take a deeper look at  this code since i hear the talk and would like a reason .

**Comment by Ashwani44** [comment]
@lukehammer Did you find any particular reason why i am getting the above error ?

**Comment by lukehammer** [comment]
No I could no get it to build in my environment. I try to spend some time on it tonight

**Comment by Ashwani44** [comment]
Hi @lukehammer I tried again today but end up with the same issue :( this is really frustating. I tried changing my connection string in appsetting,json file but issue remains the same.
I am really not understanding what causing this issue !!!!

Please check my attached doc. My repo : https://github.com/Ashwani44/CleanArchitectureDemoApp
[cannot create instance of an interface.txt](https://github.com/JasonGT/NorthwindTraders/files/2691683/cannot.create.instance.of.an.interface.txt)

**Comment by JasonGT** [comment]
Hi @Ashwani44 - I've created a pull request on your repo that should get you up and running.
Good luck.
