### ISSUE TITLE
[Question] Northwind.Persistence reference in WebUI

### ISSUE THREAD

**Issue by nguyentanphu** [JasonGT/NorthwindTraders#41]
Hello, 
I'm new here. I'm really impressed with your architecture style and love it.
I have a simple question, I can't figure out why it works (build successfully). 
So in the Startup.cs you have the:

```
using Northwind.Persistence;
....
services.AddDbContext<NorthwindDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("NorthwindDatabase")));
```

But I checked the dependency it shows it has no dependencies on Northwind.Persistence. How can this configuration works? Anyone can explain this to me, this would be great help. Thanks in advanced :D.

**Comment by nguyentanphu** [comment]
Ok, I get it for now. Turns out that there's a 'feature' in dotnet core call transitive references. A ref B, B ref C. By default A can use assets of C also. If you wanna disable this behavior: https://stackoverflow.com/questions/46709000/disable-transitive-project-reference-in-net-standard-2

**Comment by NicholasMead** [comment]
The Application project references persistence.

Unlike .Net Framework, In dotnet core references are carries forward.

Hope this helps!

**Comment by nguyentanphu** [comment]
> The Application project references persistence.
> 
> Unlike .Net Framework, In dotnet core references are carries forward.
> 
> Hope this helps!
> 
> Edit: you answered your question while I was typing 😅

Haha, Thanks for the answer anyway. Yeh, I'm new to dotnet core. So this default behavior is quite strange :)
