### ISSUE TITLE
Validation applied twice when adding a 2nd validator

### ISSUE THREAD

**Issue by Patrick-Ullrich** [JasonGT/NorthwindTraders#42]
I tried the following 2 approaches to register multiple Validators and both are giving me odd behavior.

1. 
```               
 .AddFluentValidation(fv =>
                {
                    fv.RegisterValidatorsFromAssemblyContaining<QueryValidator1>();
                    fv.RegisterValidatorsFromAssemblyContaining<QueryValidator2>();
                });
```

This will build and run, but every Validator is being run twice. This means if I have a rule like so:
```RuleFor(v => v.SomeProp).NotEmpty();```

the result with be:
["SomeProp can not be Empty", "SomeProp can not be Empty"]

Other approach:
```                
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<QueryValidator1>())
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<QueryValidator2>())
```

on app.UseMvc() i get:

```
System.InvalidOperationException: 'Sequence contains more than one matching element'
```

```
System.Linq.Enumerable.SingleOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
FluentValidation.AspNetCore.FluentValidationObjectModelValidator..ctor(IModelMetadataProvider modelMetadataProvider, IList<IModelValidatorProvider> validatorProviders, bool runMvcValidation) in FluentValidationObjectModelValidator.cs
```

Any idea?

**Comment by eb-clickfusion** [comment]
You only need to add this line once (doesn't matter what type). As the comments state:

> **RegisterValidatorsFromAssemblyContaining**
> Registers all validators derived from AbstractValidator within the assembly containing the specified type

**Comment by Patrick-Ullrich** [comment]
@eb-clickfusion thank you for that quick reply.

You are right, just adding QueryValidator1 worked. QueryValidator2 does get applied as well.
