### ISSUE TITLE
[Question] Why Application Layer contains Exceptions

### ISSUE THREAD

**Issue by musaalp** [JasonGT/NorthwindTraders#43]
As described in /Domain/ReadMe.md, it says 

> This will contain all entities, enums, **exceptions**, types and logic specific to the domain.

I wonder why we store exceptions in Application Layer,
My question is, should we store the exceptions in the related layer or all the exceptions must be in Domain Layer thus other Layers can access it.

**Comment by rafaelcgdf** [comment]
Just my two cents: from what I understand exceptions in the application layer will be business rules exceptions, some sort of invalid state of your application

**Comment by JasonGT** [comment]
Remember that the Application layer contains business logic, or logic specific to this application. This type of logic would not typically be shared across applications.

The Domain layer contains enterprise logic, logic specific to the company that could be shared across applications.

So the exceptions in the Application layer are related to application logic, and those in the Domain layer are related to Domain logic.

Hope this helps, thanks for the question.

**Comment by musaalp** [comment]
yes it helped.

thank you.
