### ISSUE TITLE
[Question] Domain Entity Collection without private set

### ISSUE THREAD

**Issue by rafaelcgdf** [JasonGT/NorthwindTraders#44]
Hi Jason,

Good job setting up this repo, it contains really good guidelines.

I have a question related to the domain entity Order, inside it has a ICollection of OrderDetail which doesn't have a private set.

The other entities I look at it all have collections with private set, I think I remember from your video that the reasoning behind is to grantee that the collection is always initialized and dev are not confused if the collection was initialized before or not.

**Comment by JasonGT** [comment]
The reason was related to the Northwind Initializer, it was accessing the collection directly to seed the database. This has been fixed now. Thank you.
