### ISSUE TITLE
OData Core

### ISSUE THREAD

**Issue by lelong37** [JasonGT/NorthwindTraders#48]
Does this architecture support OData Core? 

https://www.nuget.org/packages/Microsoft.OData.Core/ (3.5 million downloads for Core), this is an extremely heavily used library and the answer for having something comparable to GraphQL from other stacks in .NET Core.

**Comment by lelong37** [comment]
Are you guys willing to accept a PR that has OData implemented?

**Comment by JasonGT** [comment]
Hi and thanks for the question. Appreciate the offer but this is not something I am ready to incorporate. Please feel free to fork and implement - I'd love to check it out when you're done.

Thanks and good luck.

**Comment by hakimio** [comment]
@lelong37 did you try to integrate OData Core? 
Any suggestions/examples how it could work?

**Comment by hakimio** [comment]
@lelong37 What do you think about updating [maldworth/ODataWithOnionCQRS](https://github.com/maldworth/ODataWithOnionCQRS)?

**Comment by JasonGT** [comment]
Apologies, it's not something I've focused on. The resource above might be good, but it looks quite old. Suggest the following:

- https://www.youtube.com/watch?v=ZCDWUBOJ5FU
- https://github.com/damienbod/AspNetCoreOData
- Google - "ASP.NET Core 2.2 with OData"

Good luck.

**Comment by PeterJD** [comment]
Well consider reading this artical before using oData
https://www.ben-morris.com/netflix-has-abandoned-odata-does-the-standard-have-a-future-without-an-ecosystem/

**Comment by lelong37** [comment]
@JasonGT let me know if you guys would accept pr for OData.
