### ISSUE TITLE
[Question] Entity Primary Key Design

### ISSUE THREAD

**Issue by projectzerotohero** [JasonGT/NorthwindTraders#49]
Hi @JasonGT 

I'm quite curious about the reasoning behind the Primary Keys of Entities like this one
https://github.com/JasonGT/NorthwindTraders/blob/a4ed2887e052a7495bab6d092c03df9202d1d78b/Northwind.Domain/Entities/Customer.cs#L12

then configuring the table column like this
https://github.com/JasonGT/NorthwindTraders/blob/a4ed2887e052a7495bab6d092c03df9202d1d78b/Northwind.Persistence/Configurations/CustomerConfiguration.cs#L14

To keep things simpler, I am thinking of Inheriting from a BaseEntity that implements something like this
```
    public interface IEntity<TKey>
    {
        TKey Id { get; set; }
    }
```

If we have uniform `Id` field for the Entities, we can use Automapper to auto map the Primary keys for these
https://github.com/JasonGT/NorthwindTraders/blob/a4ed2887e052a7495bab6d092c03df9202d1d78b/Northwind.Application/Customers/Commands/CreateCustomer/CreateCustomerCommandHandler.cs#L27

https://github.com/JasonGT/NorthwindTraders/blob/a4ed2887e052a7495bab6d092c03df9202d1d78b/Northwind.Application/Customers/Commands/CreateCustomer/CreateCustomerCommand.cs#L7

Can you share your thoughts on how and why you came up with this design? 
Maybe I am missing some key points here.

**Comment by JasonGT** [comment]
Hi @projectzerotohero. The above suggestions are great, and you could certainly take that approach. This is similar to the approach taken in https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/BaseEntity.cs. 

The reason for the current approach is that the solution is based on a very old demo database from MS Access, and I haven't changed the schema in any way. The entities were generated using EF Core CLI.

Thank you.

**Comment by projectzerotohero** [comment]
Got it. 
Thanks @JasonGT!
