### ISSUE TITLE
How can i run this project?

### ISSUE THREAD

**Issue by AdrianoFSilva01** [JasonGT/NorthwindTraders#52]
![imagem](https://user-images.githubusercontent.com/46226901/50523574-d385a980-0ac8-11e9-9efd-8b22e60233d5.png)

**Comment by JasonGT** [comment]
The steps to run the project are listed in the ReadMe under setup; https://github.com/JasonGT/NorthwindTraders/blob/master/ReadMe.md#setup. Looking at the above error, you seemed to have forgotten step 4. Good luck.
