### ISSUE TITLE
Global Log integration in NorthwindTraders  (RoadMap)

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#53]
please Add Global Log integration in NorthwindTraders

**Comment by JasonGT** [comment]
Hi again @CodeRapp3r. Global logging is already supported. Anytime you want to log, simply inject ILogger<T> and start logging. Of course, you will need to configure the relevant logging providers. You can learn more here; https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2.

All the best.
