### ISSUE TITLE
SignalR integration in NorthwindTraders  (RoadMap)

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#54]

**Comment by CodeRapp3r** [comment]
SignalR integration in NorthwindTraders  (RoadMap)

**Comment by ardalis** [comment]
Not sure this is terribly helpful but my DDD Fundamentals course on Pluralsight uses a clean architecture approach and demonstrates integrating SignalR into the mix, along with having it respond to Domain Events. The source is available from Pluralsight which you should be able to get with a trial membership if you're not already a subscriber. It's .NET, not .NET Core.

**Comment by JasonGT** [comment]
> Not sure this is terribly helpful but my DDD Fundamentals course on Pluralsight uses a clean architecture approach and demonstrates integrating SignalR into the mix, along with having it respond to Domain Events. The source is available from Pluralsight which you should be able to get with a trial membership if you're not already a subscriber. It's .NET, not .NET Core.

Awesome course - highly recommended. Very relevant.

**Comment by JasonGT** [comment]
Hi again @CodeRapp3r. I've added this to the roadmap - https://github.com/JasonGT/NorthwindTraders/projects/1#card-17415317.

**Comment by pranavpatil19** [comment]
Thank you
