### ISSUE TITLE
Repository pattern and IoC

### ISSUE THREAD

**Issue by raminassar** [JasonGT/NorthwindTraders#55]
I'd rather to continue using repository and IoC pattern in my projects but I liked the structure of the solution. Can anyone share how they can add those two principles in this project structure and remove the dependency between persistence and presentation layer?

**Comment by ardalis** [comment]
See https://github.com/dotnet-architecture/eShopOnWeb (full sample; Microsoft reference project with eBook)
and
https://github.com/ardalis/CleanArchitecture (solution template suitable to use as a solution starting point)

**Comment by JasonGT** [comment]
Thanks @ardalis, both great resources. @raminassar you should also have a read through https://deviq.com/repository-pattern/ and https://deviq.com/specification-pattern/.

**Comment by raminassar** [comment]
@ardalis @JasonGT Thank you guys
