### ISSUE TITLE
Found Trojan:Win32/Cloxer.D!cl in slides pdf

### ISSUE THREAD

**Issue by alexpacer** [JasonGT/NorthwindTraders#56]
Hi guys, I downloaded this repository and immediately Windows Defender Pops up with this warning and removed the file. 
![2019-01-03 13_40_17-windows defender security center](https://user-images.githubusercontent.com/733219/50624658-568d8080-0f5d-11e9-8e97-69d430fa3257.png)

Anyone git the same message?

**Comment by JasonGT** [comment]
I downloaded a fresh copy and ran a Windows Defender scan on the directory with the following results:

![image](https://user-images.githubusercontent.com/1988321/50624734-c3f5dd00-0f6e-11e9-836f-001b247ba337.png)

Anyone else able to try?

**Comment by JasonGT** [comment]
FYI

![image](https://user-images.githubusercontent.com/1988321/50624785-0ddec300-0f6f-11e9-9b01-1b2290de5bd0.png)

**Comment by alexpacer** [comment]
Hi @JasonGT , 

Sorry for the false alarm. 
I think its might be the workstation that i was working on having lake of security center update. 
I tried several other PC with clean download of the repository and it has no problem at all.

![2019-01-03 14_16_05-mcafee endpoint security](https://user-images.githubusercontent.com/733219/50625364-a753a800-0f62-11e9-9c83-d2f074050ed1.png)

**Comment by JasonGT** [comment]
No worries and thank you. Hope you get it sorted.
