### ISSUE TITLE
[Question] Add user details in the loggingbehavior

### ISSUE THREAD

**Issue by AdrianoAE** [JasonGT/NorthwindTraders#57]
Hello,

In the RequestLogger
```
public Task Process(TRequest request, CancellationToken cancellationToken)
{
    var name = typeof(TRequest).Name;

    // TODO: Add User Details

    _logger.LogInformation("Northwind Request: {Name} {@Request}", name, request);

    return Task.CompletedTask;
}
```
How would the User Details be implemented?

Best Regards,
Adriano AE.

**Comment by AdrianoAE** [comment]
@jaumemilian Hello, I still don't know how to do it, I've been looking how eShopOnContainers work with authentication and I think (haven't tested anything yet) that we could have a interface that would be implemented in the Infrastructure Solution like the NotificationService in this project) that would ask a IdentityService the current user and return the required user information (for example: UserId, Name).

Files mentioned: 
[NotificationService.cs](https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.Infrastructure/NotificationService.cs) (but returning the user information to the application)
[eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Ordering/Ordering.API/Infrastructure/Services)

Can't give anything concrete since I haven't done anything yet. Having been working on other parts of my project.

Hope this can help something.

Best regards,
Adriano AE.

**Comment by Ilchuk-Mihail** [comment]
You can inject IHttpContextAccessor and gets all needed information for logs (userId, roles, userName, etc...) from Claims.

**Comment by jaumemilian** [comment]
Thanks both for the answers :)

> You can inject `IHttpContextAccessor `and gets all needed information for logs (`userId, roles, userName`, etc...) from Claims.

If I decide to build a console application on top of the current Northwind Core, how I would populate this IHttpContextAccessor?

Regards,
Jaume

**Comment by Ilchuk-Mihail** [comment]
@thiagospassos 
> If I decide to build a console application on top of the current Northwind Core, how I would populate this IHttpContextAccessor?

This method works, if you have authorization, and have some claims added to the Bearer token. 
And I assume this works only for web. 

If you build console application, I guess you don't have any authorization, and users. And you don't need to log any user info in this case.

**Comment by jaumemilian** [comment]
> @thiagospassos
> 
> > If I decide to build a console application on top of the current Northwind Core, how I would populate this IHttpContextAccessor?
> 
> This method works, if you have authorization, and have some claims added to the Bearer token.
> And I assume this works only for web.
> 
> If you build console application, I guess you don't have any authorization, and users. And you don't need to log any user info in this case.

Yes, the issue that I see is that I don't want to change the application layer in case of building other presentation on top of it. And could be I want to log the Windows User or other custom User information, with the same code in the PipelineBehaviour.
With that approach I think we couple the application layer with the HttpContext, which from my understanding should be agnostic to how the application is presented.
Could be I'm misunderstanding something.

**Comment by JasonGT** [comment]
Thanks for the question. To implement, and support multiple clients such as console and Web UI, I would recommend adding a custom ICurrentUser interface to the application layer. The client would provide it's own implementation and wire up with dependency injection. So a web UI might use IHttpContextAccessor within the implementation, whereas a console app might use windows authentication or something else.

I'll incorporate this as an example once I get ASP.NET Identity up and running. I've added it to the roadmap; https://github.com/JasonGT/NorthwindTraders/projects/1#card-15959729.

**Comment by jaumemilian** [comment]
Thanks Jason,

We already did like that defining the interface IUserIdentity at application layer, and injecting it from presentation

Regards,
Jaume

**Comment by BionStt** [comment]
> Thanks Jason,
> 
> We already did like that defining the interface IUserIdentity at application layer, and injecting it from presentation
> 
> Regards,
> Jaume

could you please share your iuseridentity ? i need to learn more about this.
