### ISSUE TITLE
@JasonGT You are serious about NorthwindTraders project

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#59]
@JasonGT You are serious about NorthwindTraders project

i watching this repository from last 2 month nothing happen.Month Of the project contributor is inactive.
So Please tell us what is timeline of this changes. 

So let us know ,

now  i am not following this repository.. because no documentation,all contributor is inactive and new regular update

**Comment by rafalschmidt97** [comment]
![screenshot 2019-01-31 at 09 50 58](https://user-images.githubusercontent.com/14861637/52042543-bca9fb00-253d-11e9-9d32-ee21a9cddd0e.png)

Boys he is alive! 🤓

**Comment by JasonGT** [comment]
Yes, sorry - still alive. I've been flat out lately with work, conferences, and family. I'm hoping to have some time in the coming months to add some new features.

Sorry @CodeRapp3r - I know you would like more - as would I - however right now I just don't have the time.
