### ISSUE TITLE
Where does GraphQL fit in clean code architecture?

### ISSUE THREAD

**Issue by simont789** [JasonGT/NorthwindTraders#60]
Hi, 

I have only recently started to look at GraphQL. Coming across  to this repository also recently, I'm wondering where does GraphQL fit in this context. 

From my understanding, GraphQL solves the problem of having too many API endpoints by providing a more flexible querying system: 
- By using GraphQL, where does it fit?
  - is it just another way of writing the application layer? Instead of writing commands and queries, you define the application layer with queries and resolvers etc... 
  - OR, should it exists as a layer between WebUI and Application layer? 
  - OR, between the Application layer and Persistence layer?
- Can GraphQL reduce the amount of code written in the Application layer? Or reduce the maintenance required in the future? Could it make it better the application layer better?
- However by doing this, you probably will need to dependent on a library to map GraphQL queries to EF core, which it does exists. Does it breaks clean code architecture? 

Let me know if this is not the right place to ask questions here. Cheers!

Simon 

I'm a young software developer who haven't finished reading the Clean Architecture. Love the content here. It answers many questions that I've had over in previous projects. So thank you :)

**Comment by erikshafer** [comment]
Apologies if this isn't considered construcive, but I would like to echo feedback regarding where GraphQL would best fit with this type of (clean) architecture.

**Comment by JasonGT** [comment]
Hi @simont789 - thanks for the question. Apologies, however I've not had the opportunity to explore this in detail at this stage. It's not on my radar right now, but I may explore it in the future.

Sorry I couldn't be of help. Good luck with your research. 😄
