### ISSUE TITLE
Why Persistence layer is referencing the Domain Layer ?

### ISSUE THREAD

**Issue by oyont** [JasonGT/NorthwindTraders#61]
According to modelling schema in pdf slides Domain layer is in the core of the application and only application layer should reference it. But in the solution persistence layer referencing domain layer because of the dbcontext. Is that correct way ?

**Comment by rafalschmidt97** [comment]
Read some older issues. You gonna find many answers for you questions (even for this one). This is about simplicity. Without persistence <-> domain you will be forced to have ONE ANOTHER entity which will do the same shit as the domain (and you will need to map them every time). I don't see any advantages of this solution. 

If you will go deeper into this project (for example try to code this from scratch), you will find more inconsistency like this. There's always gonna be a tradeoff.

**Comment by ruimaciel** [comment]
@oyont has a point, and I would also add that the application layer depending on the persistence layer is also one aspect that goes against the clean architecture's dependency rule: ["Nothing in an inner circle can know anything at all about something in an outer circle."](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

**Comment by JasonGT** [comment]
Thanks for the query - we had a really good discussion here - https://github.com/JasonGT/NorthwindTraders/issues/18.
