### ISSUE TITLE
Add Razor Pages to Roadmap

### ISSUE THREAD

**Issue by larkydoo** [JasonGT/NorthwindTraders#62]
In one of your talks I believe you mentioned wanting to integrate Razor Pages into your sample. I'm not seeing that in the Roadmap. Are you still planning to add it? I would much appreciate it.

Thanks!

Laurie

**Comment by JasonGT** [comment]
Hi Laurie, thanks added to project roadmap. A heads up - I'm keen to see this happen, but I am not sure when it will be ready.

**Comment by JasonGT** [comment]
Also, did you see this repo - https://github.com/jbogard/ContosoUniversityDotNetCore-Pages. It's awesome.
