### ISSUE TITLE
Question about the CustomerDetailModel 

### ISSUE THREAD

**Issue by scossgrove** [JasonGT/NorthwindTraders#66]
Issue:
The GetCustomerDetailQueryHandler handle method constructs the CustomerDetailModel manually, yet the CustomerDetailModel has a Create static method for doing the same. 

Question(s):
Why has the project elected to not use the create method here? 
Doesn't this break the DRY principle? 
Am I missing something simple here?

**Comment by JasonGT** [comment]
> Why has the project elected to not use the create method here?

This is something that I missed, thanks for pointing it out.


> Doesn't this break the DRY principle?

Yes, the mapping logic is in two places.


> Am I missing something simple here?

Not at all. It could be updated as follows:
```
return CustomerDetailModel.Create(entity);
```

Much cleaner.
