### ISSUE TITLE
Question: Clean Code Query

### ISSUE THREAD

**Issue by scossgrove** [JasonGT/NorthwindTraders#67]
Background:
So if I understand correctly the principles of Clean Architecture, the only reliance that the Application Layer should have is inward to the Domain. But if this is the case then why does the Northwind.Application have a reference to the Persistence layer?

Even more stand to me is the GetCustomerDetailQueryHandler having a direct dependency on the implemenation of the persistence layer's NorthwindDbContext.

Question:
Why is the above acceptable if the project is trying to be constructed as per Clean Architecture principles?

**Comment by JasonGT** [comment]
Hello and thanks for you interest.

> Why is the above acceptable if the project is trying to be constructed as per Clean Architecture principles?

This is discussed in detail here; https://github.com/JasonGT/NorthwindTraders/issues/18.
