### ISSUE TITLE
AsyncRequestHandler

### ISSUE THREAD

**Issue by space-alien** [JasonGT/NorthwindTraders#68]
Just wondering if there is any reason not to use MediatR's [`AsyncRequestHandler`](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs) which avoids the Unit return type?

https://github.com/jbogard/MediatR/wiki

**Comment by JasonGT** [comment]
No reason. I was reviewing the documentation myself and thought this would be much cleaner. I don't really like messing about with the Unit return type either. I'll probably use it in the future.

**Comment by JasonGT** [comment]
Just a follow-up, I tried this today, this doesn't work very well. The `AsyncRequestHandler` is defined as follows:

```
    public abstract class AsyncRequestHandler<TRequest> : IRequestHandler<TRequest>, IRequestHandler<TRequest, Unit> where TRequest : IRequest
    {
        protected AsyncRequestHandler();

        protected abstract Task Handle(TRequest request, CancellationToken cancellationToken);
    }
```

You can see the `Handle` method is protected. Not so easy to unit test.

I'll close this off, however feel free to let me know if you have any suggestions.
