### ISSUE TITLE
Docker image doesn't seem to work?

### ISSUE THREAD

**Issue by SirwanAfifi** [JasonGT/NorthwindTraders#70]
When I run/build the image using docker-compose I get this error on the console:
```
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195584700Z Application startup exception: System.AggregateException: One or more errors occurred. (Failed to start Node process. To resolve this:.
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195611100Z 
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195616200Z [1] Ensure that Node.js is installed and can be found in one of the PATH directories.
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195620700Z     Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195625000Z     Make sure the Node executable is in one of those directories, or update your PATH.
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195629400Z 
[36mMyProject.web_1  |[0m 2019-02-15T10:15:44.195633500Z [2] See the InnerException for further details of the cause.) ---> System.InvalidOperationException: Failed to start Node process.
```

I have also reported the issue here (https://github.com/Microsoft/aspnet-docker/issues/164)

**Comment by NicholasMead** [comment]
Node is not being installed into the base/runtime continer, only the intermediate build container. The same is true for the source code.

The issues with using hot module replace within the docker environment is that the code (and node) need to be included into the runtime container, and this is both messy and inefficent for prod. I recomend that you use pre-compiler commands to include hot module replace in your local builds, and let Docker stay untouched for prod builds.

Hope this helps

**Comment by JasonGT** [comment]
Hi @SirwanAfifi - thanks for raising. And @NicholasMead - thanks for your comments.

Although containerisation is an important topic, it's not something that I am looking to specifically include within this solution. If someone wants to resolve this issue and submit a pull request, that will be good. Otherwise I'll probably pull out the docker files in the near future.

Apologies @SirwanAfifi , I know this is not very helpful to get you up and running. Hopefully @NicholasMead comments will get you unblocked.

**Comment by SirwanAfifi** [comment]
Thanks, @NicholasMead @JasonGT 
I asked the question on StackOverflow, and found the solution, thank you, guys :)
https://stackoverflow.com/questions/54712876/net-core-docker-image-doesnt-seem-to-have-node-js-installed/54713999#54713999
