### ISSUE TITLE
ValueObject.cs GetHashCode

### ISSUE THREAD

**Issue by cphillips83** [JasonGT/NorthwindTraders#72]
If I recall, GetHashCode is used in some objects for equality checks right?

Shouldn't this be something like...

```
        public override int GetHashCode()
        {
            return GetAtomicValues()
                .Select(x => x != null ? x.GetHashCode() : 0)
                .Aggregate((x, y) => (x * 397) ^ y);
        }
```

So that if you had a `Point` object with `int X, Y` and one with `X = 1, Y = 2` and another `X = 2, Y = 1` they would have different hashcodes. Right now, even though the objects are different their hash codes are both 3.

**Comment by JasonGT** [comment]
Hi @cphillips83. I wasn't sure, so I created a couple of unit tests based on your example. It seems to work fine. Thoughts?

**Comment by JasonGT** [comment]
Closed, it seems to work for given test case.

**Comment by cphillips83** [comment]
Sorry that it took me so long to get back to this. .NET has come a long way and this may no longer apply, one could open the source up and look at the dictionary and hashset implementations to see.

Your tests will of course pass because you are using Equals, which is running your Equals code in the atomic comparison which is doing nothing more than equal checks against the real fields.

Where this becomes an issue is that the types I listed above (and more) store the data based on the objects hash code in buckets, which means `Point(1,2)` and `Point(2, 1)` will generate the same hashcode and therefore a hash collision which will degrade performance.

Also as I mentioned you are testing equality in your unit tests and not GetHashCode, you should have a test to Assert `p1.GetHashCode() != p2.GetHashCode()` because the specification states that the HashCode should attempt to generate.

For reference, an example of a well used library implementing this on structs for example.

https://github.com/MonoGame/MonoGame/blob/master/MonoGame.Framework/Vector3.cs


To be honest, it probably doesn't really apply to this library since the amount of data being handled and valueobjects being stored in massive hash buckets is probably small. None the less it is a performance gain to prevent hashing collisions.

**Comment by cphillips83** [comment]
In addition  https://blogs.msdn.microsoft.com/ericlippert/2011/02/28/guidelines-and-rules-for-gethashcode/
