### ISSUE TITLE
Mirgration  MediatR 5.x to 6.0 

### ISSUE THREAD

**Issue by pranavpatil19** [JasonGT/NorthwindTraders#73]
The type 'IRequest<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null'.	

please help Mirgration  MediatR 5.x to 6.0

**Comment by xucito** [comment]
Check that all referenced projects are also on MediatR 6.0. I had the same error because one of my referenced projects was on 5.1.

**Comment by JasonGT** [comment]
Check out the associated commit, thanks.
