### ISSUE TITLE
DTO vs Model

### ISSUE THREAD

**Issue by mantasaudickas** [JasonGT/NorthwindTraders#74]
Just wondering, why some objects in Application layer are named as Dto and others as Model?

**Comment by rafalschmidt97** [comment]
He use models if there’s need to add some extra logic or to have a wrapper for many dto’s (data aggregation - from ddd). You can also add some extra booleans (as a flags) if you want.

**Comment by mantasaudickas** [comment]
Thanks for explanation.

**Comment by torturegenitale** [comment]
I see mapping in some DTOs. Is not it considered as logic?

**Comment by koniecdev** [comment]
Anyway, the "main" dto is always called VM as I see, and any nested dto is actually called DTO, right?
