### ISSUE TITLE
SQL server exception during run

### ISSUE THREAD

**Issue by junsp** [JasonGT/NorthwindTraders#8]
Hi

As I follow your readme, I get SQL error

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

I have tried to do in the package console:
update-database

doing following in the webapi project throws exception in the SQL server
dotnet run

I have tried opening 1433 default SQL server port and still not working.

**Comment by JasonGT** [comment]
Hi,

The Web API project connects to SQL Server using the . (dot) alias - this points to the local machine instance. Review the connection string here; https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.WebApi/appsettings.json. You might need to updated dependent on the configuration of your environment, for example if you are using a named instance or if you have not windows authentication.

You could install SQL Server Management Studio and try connecting to . (dot) to see if everything is working normally.

Good luck!

**Comment by junsp** [comment]
I just changed '.' to '(localdb)\\mssqllocaldb' and used 'update-database' in the package manager console.
Now I see all the tables and database in local.

**Comment by JasonGT** [comment]
Awesome, thanks for sharing your solution.
