### ISSUE TITLE
Suggestion: Move NorthwindDbContext to Application

### ISSUE THREAD

**Issue by MikaelElkiaer** [JasonGT/NorthwindTraders#81]
What bothers me the most, about the current dependency diagram, is the arrow from the NorthwindTraders.Application project to the NorthwindTraders.Persistance project.

However, seeing as Application could and should use NorthwindDbContext, why not move that to Application?
Alternatively, move it to a a sub-namespace of Application: NorthwindTraders.Application.Data, or even a new layer within Core: NorthwindTraders.Data.

However, as I am not an expert in EF, I do not know how to handle the configurations currently applied in NorthwindDbContext: https://github.com/JasonGT/NorthwindTraders/blob/29c66f398c17ddf9ba15bbcdbcd56487f48fb67a/Northwind.Persistence/NorthwindDbContext.cs#L40
This should be possible though, right - having the configurations applied outside NorthwindDbContext, but within Persistance?

As I see it, this would remove the dependency, having a shared dependency for Persistance and Application that is beneath both those layers.

**Comment by rasmuseeg** [comment]
The reason is that the persistence layer handles all database logic. And can be replaced, not that it should or will be. I belive this has already been discusess on other topics. See #61

**Comment by MikaelElkiaer** [comment]
@rasmuseeg I'd argue that it would still do that. The NorthwindDbContext would only dependend on `Microsoft.EntityFrameworkCore` and `Northwind.Domain.Entities` - then it only says something about the entities and their relations and not 'database logic'. The persistence layer would build on top of that with actual database configurations.

**Comment by JasonGT** [comment]
You could move it to Application, but it's not the approach that I would take. I think the main issue is the dependency from Application > Persistence, it should be inverted. Let's look at a couple of options.

Firstly, we can do so by using the Unit of Work and Repository patterns. To implement within this solution, I'd recommend adding unit of work and repository interfaces to the Application layer, and implementing these interfaces within the Persistence layer. Remove all references to the DbContext in the Application layer, instead utilising the new unit of work and repository interfaces. You can then correctly invert the dependency on Persistence. This is the cleanest approach, you will then be independent of the framework (EF Core).

Alternatively, you can create an INorthwindDbContext in the Application layer. The interface will include all DbSet properties and a SaveChanges method. Then add this interface to the NorthwindDbContext class in the Persistence layer. Finally, within the Applciation layer, replace all references to NorthwindDbContext with the interface INorthwindDbContext. Invert the dependency on Persistence and add NuGet package reference to Microsoft.EntityFrameworkCore within the Application layer. This approach is good, as the dependency on Persistence is correctly inverted. It however is not quite so clean as the first, as it means that the Application layer depends on Microsoft.EntityFrameworkCore. Considering that Application already had an indirect dependency on this package, it is not a big deal.

Which option you will go for, whether it be the one demonstrated in the video or one of the two above, will depend entirely on your non-functional requirements.
