### ISSUE TITLE
Transaction management, ActionFilter or Pipeline filter?

### ISSUE THREAD

**Issue by nixonad** [JasonGT/NorthwindTraders#82]
Unless I'm missing something, I don't see any transaction management in this sample. 
Typically we'd want to create a single transaction over the whole request to the API for Commands, and any mediator requests which execute in the flow automatically take part in the transaction.
We can either start and end such a transaction in an ActionFilter in the MVC pipeline, or in a Mediator Pipeline. If we use and ActionFilter then the mediator bits never need to know anything about transactions, it also encapsulates the start and end point for a user interaction clearly, in the Mediator pipeline, I imagine it'd be a little more difficult to ascertain when a request is part of an existing transaction already or if one should be started/ended.

Anyone have any thoughts/recommendations on this? 

Thanks

**Comment by JasonGT** [comment]
With this approach, everything that needs to occur as a transaction would be implemented within a single command. There are alternative approachs, such as a single transaction across a single request, but I prefer the simplicity of the first approach. Typically, the command will be implementing some business case, so I'll encapsulate everything related to that case within the command.

**Comment by nixonad** [comment]
Thanks for the feedback @JasonGT, I implemented a transaction per request. 
In my system I'm publishing notifications/events after most commands which in turn fire additional commands, thereby enabling the original command to remain contained and reduce it's knowledge of the rest of the system.
In a more advanced environment I'd have to persist the events and ensure they get processed out of band and handle any errors in the event processing separately, mediator allows me to do this simply (if I don't processes the notifications asynchronously) and all I have to do is wrap everything in a transaction.
Later on when using an out-of-band pub/sub system becomes necessary it should be relatively easy to switch out MediatR's system.
Thanks again.
