### ISSUE TITLE
enum in domain layer, but i want to use it in application .  how can i do that?

### ISSUE THREAD

**Issue by teamsmiley** [JasonGT/NorthwindTraders#84]
```
namespace Domain.Entities
{
  public class MyNode : EntityBase
  {
    public enum NodeStatus
    {
      WAITING,
      RUNING,
      ERROR,
      REBOOT,
    }

    public Guid Id { get; set; }
    public string Name { get; set; }
    public NodeStatus Status { get; set; }
    public string NodeIp { get; set; }
```

**Comment by matiasromero** [comment]
Since Application references Domain, you should be able to use it.
It is a public enum.

**Comment by teamsmiley** [comment]
so like this ??
```
  public class CreateMyNodeCommand : IRequest<MyNodeDto>, IHaveCustomMapping
  {

    public string Name { get; set; }
    public RenderNode.NodeStatus Status { get; set; }
```

**Comment by teamsmiley** [comment]
i am using webapi. (presentation layer)

webapi need that enum too. isnt it?

current it take int  like this 
```
 public class MyNodesGetRequest 
  {
    public string Name { get; set; }
    public int? Status { get; set; }
```
==>  so change like this
```
 public class RenderNodesGetRequest : 
 {
    public string Name { get; set; }
    public RenderNode.NodeStatus? Status { get; set; }
}
````

but then i have to use domain layer code on present layer.

what do you think?

**Comment by matiasromero** [comment]
Yes, you can do that, but... I recommend one of the next two ways:

1. Move the enum definition outside the domain class (it can be placed in a separeted file)
`namespace Domain.Entities
{
  public class MyNode : EntityBase
  {
    public Guid Id { get; set; }
    public string Name { get; set; }
    public NodeStatus Status { get; set; }
    public string NodeIp { get; set; }
  }
  //outside class MyNode
   public enum NodeStatus
   {
     WAITING,
     RUNING,
     ERROR,
     REBOOT,
   }`

2. Add an enum class in Application, like a model, to be mapped with the enum of Domain.

`namespace Application.SharedEnums
{
  public enum NodeStatus
  {
     WAITING,
     RUNING,
     ERROR,
     REBOOT,
   }
}`

In this way you only need to use Automapper to map Application.SharedEnums.NodeStatus with Domain.Entities.NodeStatus, and you can use this Application enum in Application and in Presentation Layer.

**Comment by teamsmiley** [comment]
ah...got it i will take second approach.

thank you so much.
