### ISSUE TITLE
Question:  Anemic domain

### ISSUE THREAD

**Issue by Allann** [JasonGT/NorthwindTraders#87]
Hi, fellow brisbanite here,
watched you presentation of this on youtube today.  enjoyed it a lot, but I do have some questions:

1. Isn't this creating a very anemic domain?  You have the Create logic for customer in the handler for example, whereas it should be a method in the domain, should it not?  if not, could you elaborate why not.
2. Your domains look very EF like, i.e.  Order.CustomerId and Order.Customer, if persisting this to a document store the object would be denormalised therefore not require the child keys just the related object.

You mentioned in the talk that you wouldn't put the data annotation in the domain because they are persistence details.  I agree and you had separate config to highlight that.  Why would you not create persistence classes specific to your store type, and upon fetching the data generate you domain?  This would mean your domain doesn't change for "15 years" especially when you move the app to the cloud and use a NoSQL data store.

I'm more playing devils advocate and raising questions to provoke discussion and learn the reasoning, than to criticize the solution as I learnt a lot.

**Comment by rafalschmidt97** [comment]
Hi 🙆‍♀️
2. Please read closed issues. He already described why you should not have yet another class which describes almost the same. It’s all about simplicity. More classes = bigger codebase to maintain. But if this concept fit your needs then why not? In this project you’ll find a lot of not perfect solutions. It’s just a concept instead of production ready boilerplate to use. We should treat that as a cool repo and maybe use some parts of it as a core of next apps.

Hope you have a great day 😁

**Comment by JasonGT** [comment]
Hi @Allann,

Thanks for your questions.

> Isn't this creating a very anemic domain? You have the Create logic for customer in the handler for example, whereas it should be a method in the domain, should it not? if not, could you elaborate why not.

The rich / anemic domain model & pro / cons associated is just not a concept I'm trying to demonstrate. General advice would be that if you start to encounter duplciate of logic, such as when creating a customer, push it down to the domain.

> Your domains look very EF like, i.e. Order.CustomerId and Order.Customer, if persisting this to a document store the object would be denormalised therefore not require the child keys just the related object.

Agreed. Domain is scaffolded directly from the existing Northwind Traders database built by Microsoft.

>  Why would you not create persistence classes specific to your store type, and upon fetching the data generate you domain?

Nothing wrong with this approach. Just need to decide, do you want complexity now for potential simplicity later or complexity later for simplicity now. Consider YAGNI and then take the approach that works for your team and the system being developed.

Thanks again, glad you enjoyed the talk.
