### ISSUE TITLE
Question: Why some DTO objects don't use AutoMapper?

### ISSUE THREAD

**Issue by qazq** [JasonGT/NorthwindTraders#90]
Hi, 
In some handlers use `_mapper.Map` or `ProjectTo<>` to create DTO object, but in other handlers use `.Select(CategoryPreviewDto.Projection)`. Why don't use AutoMapper for all the DTO objects, even the object is no need to implement `IHaveCustomMapping`? Is it performance considerations? I have to write `public static Expression<Func<Product, ProductPreviewDto>> Projection` for every DTO object if I don't use AutoMapper.

Thanks :)

**Comment by JasonGT** [comment]
I need to clean this up...

**Comment by JasonGT** [comment]
Thanks, I've added this to the roadmap.
