### ISSUE TITLE
Add Authorization with ASP.NET Core Identity

### ISSUE THREAD

**Issue by JasonGT** [JasonGT/NorthwindTraders#92]
Include example of ICurrentUser within Application layer to support MediatR logging behaviours.

Include example of checking each request permission in the Application layer, e.g. restrict request to Admin role. See #88 for good suggestions.

**Comment by JasonGT** [comment]
Will do this in conjunction with the new Identity features coming in .NET Core 3, so #91 is a prerequisite.

**Comment by mhartvig** [comment]
Any hints as to how you would do this? I've also thought about using DI as suggested in #88 but I can't figure out if that is the best way to do it.

**Comment by JasonGT** [comment]
If you're working with ASP.NET Identity, using an Authorization filter (IAsyncAuthorizationFilter) combined with an ICurrentUser service is a good starting point. 

The ICurrentUser service will be resposible only storing the user Id. It might look like this:

```
public interface ICurrentUser 
{
    int Id { get; set; }
}
```

The interface will be stored in the Application layer, with the implementation in the client, in this case ASP.NET Core. Configure ICurrentUser with DI scoped to the request (AddScoped).

The authorization filter is the first to be executed in the pipeline, so this is where you can get and store the current user. Inject ICurrentUser into the filter, and set the Id if the user is authenticated.

Now, anytime you need to access the current user within a query or command, just add ICurrentUser to the constructor.

**Comment by jonakirke94** [comment]
Hi @JasonGT, trying to implement a clean architecture based on your fine repo for a school project. 

Does Authorization/Authenticaion only happen in our Web Project (Presentation Layer) or also in every request? Do we make any checks in the application layer? Or is that why you want to access the Id in your handler to manually query your database and validate access?

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.

**Comment by sas10x** [comment]
when will this ticket be closed?

**Comment by jaumemilian** [comment]
Hi @JasonGT, I see this ticket is in progress since time ago.
Is there any code example about Authorization in ApplicationLayer using the IAsyncAuthorizationFilter + CurrentUser

Thanks so much

Regards,
Jaume

**Comment by Patrick-Ullrich** [comment]
@jaumemilian I am not using IAsyncAuthorizationFilter, furthermore, I am not using Asp.net Identity, rather just a simple JwtBearer Authentication added to your Api. But I hope this still helps.

```
services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(x =>
            {
                x.RequireHttpsMetadata = false;
                x.SaveToken = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateIssuer = false,
                    ValidateAudience = false
                };
            });
```


1. Application Layer, add ICurrentUser (like @JasonGT mentioned)
```
public interface ICurrentUser 
{
    string Id { get; set; } // Note that I set it to a string here not an int
}
```

2. Add a CurrentUserMiddleware to your WebUI project.
```
    public class CurrentUserMiddleware
    {
        private readonly RequestDelegate _next;

        public CurrentUserMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context, ICurrentUser currentUser)
        {
            currentUser.Token = context.User.Claims.FirstOrDefault(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name").Value; // depending on your implementation set this to whatever claim you want to
            await _next(context);
        }
    }
```

3. Add the Middleware to your project. I am adding it after the Authorization.
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
...
            app.UseAuthentication();
            app.UseMiddleware<CurrentUserMiddleware>();
...
}
```

4. Add an implementation for ICurrentUser to your WebUI project:
```
    public class CurrentUserService : ICurrentUser
    {
        public string Id{ get; set; }
    }
```

5. Add Scoped, in your Startup.cs of your WebUI project add CurrentUserService as scoped
```
public void ConfigureService(IServiceCollection services) 
{
...
services.AddScoped<ICurrentUser, CurrentUserService>();
...
}
```

Finally, inject your ICurrentUserService wherever you need in your Application layer.

```
public class SomethingQueryHandler: IRequestHandler<SomethingQuery, Foo>
    {
        private readonly ICurrentUser _currentUser;

        public SomethingQueryHandler(ICurrentUser currentUser)
        {
            _currentUser = currentUser;
        }

        public async Task<Foo> Handle(SomethingQuery request, CancellationToken cancellationToken)
        {
             let currentUserId = _currentUser.Id;
               return new Foo();
        }
    }
```

Hope this helps. Looking forward to the implementation by Jason + .net core 3

**Comment by JasonGT** [comment]
In the new [dotnetcore3](https://github.com/JasonGT/NorthwindTraders/tree/dotnetcore3) branch, I've added an implementation using ASP.NET Core Identity. This update includes:

- Update to Infrastructure layer to included Identity
- New ICurrentUserService to inject into Application layer
- Controllers now require authentication
- Startup has been configured with identity test user and client for development and integration tests
- Integration tests have been updated to use access tokens
- MediatR pipeline behaviours - logging and performance, updated to include current user id

There is still more work today, but this is a good foundation. 

Feedback welcome.

**Comment by jaumemilian** [comment]
> In the new [dotnetcore3](https://github.com/JasonGT/NorthwindTraders/tree/dotnetcore3) branch, I've added an implementation using ASP.NET Core Identity. This update includes:
> 
> * Update to Infrastructure layer to included Identity
> * New ICurrentUserService to inject into Application layer
> * Controllers now require authentication
> * Startup has been configured with identity test user and client for development and integration tests
> * Integration tests have been updated to use access tokens
> * MediatR pipeline behaviours - logging and performance, updated to include current user id
> 
> There is still more work today, but this is a good foundation.
> 
> Feedback welcome.

Thanks for the update Jason.
I just had an overview of the code, and one thing that surprises me (and differs from what I have locally implemented) is that the implementation of CurrentUserService is in Infrastructure instead of Presentation. I thought that it was a Presentation service, isn't it? Why not?

Thanks for your time

Regards,
Jaume

**Comment by JasonGT** [comment]
Thanks a lot for the review @jaumemilian, appreciate the feedback. 
You're absolutely right, I've just moved it to presentation.
Different clients should be able to provide different implementations of ICurrentUserService.

Did you add any support to system user or anonymous user handing in your implementation? I haven't covered that at this stage.

**Comment by GFoley83** [comment]
Hi Jason,

`Include example of checking each request permission in the Application layer, e.g. restrict request to Admin role. See #88 for good suggestions.`

Did this part not make it into the PR?

If we're saying that Auth is a cross-cutting concern, in my mind we should probably be implementing permission checking as a pipeline in the Application layer, exactly like how we do for validation with `RequestValidationBehavior`. 

If permissions fail (i.e not an "admin" request) we'd throw a Permissions / Authorization exception that would be ultimately be handled by the Presentation layer
e.g. for the current WebUI project, we'd could extend the `CustomExceptionHandlerMiddleware` class to handle a `PermissionException` for example, and return a 403.

I'm assuming we'd extend `ICurrentUserService` to include some properties to store role-specific info, which could be as simple as `IsAdmin` in this example?

As to where the actual logic lives around checking the current user's permissions to see if the request should be allowed to continue i.e. the request handler can be executed, rafalschmidt97 had the idea here:
https://github.com/JasonGT/NorthwindTraders/issues/88#issuecomment-476121042 of creating an interface that extends `IRequest` such as `IAdminRequest`. This approach would work well if we used a pipeline to handle the permission checking as I mentioned above, as we could just inject `ICurrentUserService` into a pipeline that is configured to intercept all `IAdminRequest`s and then check the `IsAdmin` property on `ICurrentUserService`.

Apologies for being verbose here. Just trying to see what peoples thought are on this as I'm not a fan of having to relying on the `Authorize` attribute or having the bulk of the logic in a middleware (as with Patrick-Ullrich example above) as it over-reliant on the Presentation layer and goes against having auth as a cross-cutting concern.
