### ISSUE TITLE
Question: Migration

### ISSUE THREAD

**Issue by Hameds** [JasonGT/NorthwindTraders#97]
Hello

As I understand all migration files are in `Northwind.Persistence` project, but how you add them there? `dotnet ef migrations add` command doesn't work. here is the error messages:
![Capture](https://user-images.githubusercontent.com/1385656/55307330-7bb26200-546c-11e9-8465-281982279c9f.PNG)

**Comment by alexandercarls** [comment]
You need to change the directory to `Northwind.Persistence` instead of `WebUI`.
Otherwise, you would need to pass in the `project` and `model` args.

**Comment by Hameds** [comment]
@alexandercarls thanks for the reply. As you can see in the attached image, I've tried that one too and it's not working (look closer at the second error)
Also, I tried `project` arg in `WebUI` directory and that's not working either

**Comment by rafalschmidt97** [comment]
Or use some weird syntax like this:

ASPNETCORE_ENVIRONMENT=Development dotnet ef migrations add Initial --project XXX.Persistence --verbose

ASPNETCORE_ENVIRONMENT=Development dotnet ef database update --project XXX.Persistence --verbose

**Comment by alexandercarls** [comment]
@Hameds Sorry, I wrote this while in a hurry and didn't notice it. I suggest trying out to change the TargetFramework in the csproj file to `netcoreapp2.2`. This was changed a couple of weeks ago in this comment https://github.com/JasonGT/NorthwindTraders/commit/29c66f398c17ddf9ba15bbcdbcd56487f48fb67a#diff-85215c825ed3f05a55e4122038cee557

**Comment by majid-joghataey** [comment]
Source: [Microsoft](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects)

1. Right-clicking the .NET Core app in your project (Northwind.WebUI)

2. Clicking Set as StartUp Project

Package Manager Console
Default Project Northwind.WebUI
PM> `Add-Migration NewMigration -Project Northwind.Persistence`

**Comment by Hameds** [comment]
@majid-joghataey As I mentioned, I tried `-p` and it didn't work. take a look at the second error in attached image

**Comment by majid-joghataey** [comment]
@Hameds  I had this problem, as I explained, was resolved.
Instead of using this `dotnet ef migrrations add test`
Try this command
Northwind.WebUI> `Add-Migration test -Project Northwind.Persistence`

**Comment by JasonGT** [comment]
Please try again, it should be working now using `dotnet ef migrations add`.
