### ISSUE TITLE
[Feature request] OData Core integration

### ISSUE THREAD

**Issue by hakimio** [JasonGT/NorthwindTraders#98]
It would make a lot of sense if WebUI project would use [OData **standard**](https://www.odata.org/) for the REST API instead of trying to reinvent the wheel with custom web api. 
@JasonGT is there any reason you are against integrating [OData Core](https://www.nuget.org/packages/Microsoft.AspNetCore.OData)?

**Comment by JasonGT** [comment]
Hi @hakimio - thanks for the feature request. The purpose of the repository is evolving, right now it's to demonstrate a number of concepts relating to the Clean Architecture talk. I'm not against implementing OData, it's just not a concept that I am seeking to demonstrate within this solution.
